[functions.openai-proxy]
verify_jwt = true
cors = {
  enabled = true,
  allowed_origins = ["*", "http://localhost:5173", "https://localhost:5173", "http://127.0.0.1:5173", "https://127.0.0.1:5173"],
  allowed_methods = ["POST", "GET", "OPTIONS"],
  allowed_headers = ["authorization", "x-client-info", "apikey", "content-type", "origin"],
  exposed_headers = []
}