[functions.openai-proxy]
verify_jwt = true
cors = {
  enabled = true,
  allowed_origins = ["*"],
  allowed_methods = ["POST", "OPTIONS"],
  allowed_headers = ["authorization", "x-client-info", "apikey", "content-type"],
  exposed_headers = []
}