/**
 * ID Mapping Module
 *
 * Maps element IDs between PLoT format and UI format.
 * Critical for:
 * - Edge IDs: PLoT uses "from::to::index" format
 * - Highlights: IDs in responses need mapping to UI elements
 * - Drivers: IDs in drivers_payload need mapping
 *
 * Edge ID Format:
 * - PLoT: "price::demand::0" (from::to::index)
 * - UI: UUID or custom string generated by ReactFlow
 *
 * The index handles parallel edges (multiple edges between same nodes).
 */

import type { Node, Edge } from '@xyflow/react'
import type { Highlight } from '../types/primitives'

// =============================================================================
// Types
// =============================================================================

export interface IdMappingResult {
  /** Successfully mapped IDs */
  mapped: string[]

  /** IDs that could not be mapped */
  unmapped: string[]
}

// =============================================================================
// Edge ID Mapping
// =============================================================================

/**
 * Maps PLoT edge ID format ("from::to::index") to UI edge ID.
 *
 * The index is critical for parallel edges (multiple edges between same nodes).
 * We match by:
 * 1. First checking if any UI edge has a stored plot_id matching exactly
 * 2. Then finding the Nth edge (by stable ordering) between source/target
 *
 * @param plotEdgeId - Edge ID in PLoT format
 * @param uiEdges - UI edges to search
 * @returns UI edge ID or null if not found
 */
export function mapPloTEdgeId(plotEdgeId: string, uiEdges: Edge[]): string | null {
  // First: check if any edge has this exact plot_id stored
  const directMatch = uiEdges.find(e => (e.data as any)?.plot_id === plotEdgeId)
  if (directMatch) {
    return directMatch.id
  }

  // Parse PLoT format: "from::to::index"
  const parts = plotEdgeId.split('::')
  if (parts.length < 2) {
    if (import.meta.env.DEV) {
      console.warn('[IdMapping] Invalid PLoT edge ID format:', plotEdgeId)
    }
    return null
  }

  const [from, to, indexStr] = parts
  const index = indexStr ? parseInt(indexStr, 10) : 0

  // Find ALL edges matching source/target, sorted by ID for stable ordering
  const matchingEdges = uiEdges
    .filter(e => e.source === from && e.target === to)
    .sort((a, b) => a.id.localeCompare(b.id))

  if (matchingEdges.length === 0) {
    if (import.meta.env.DEV) {
      console.warn('[IdMapping] No UI edge found for PLoT ID:', plotEdgeId, { from, to })
    }
    return null
  }

  // Get the Nth edge (by index)
  if (index >= matchingEdges.length) {
    if (import.meta.env.DEV) {
      console.warn('[IdMapping] Index out of range for PLoT ID:', plotEdgeId, {
        from,
        to,
        index,
        availableCount: matchingEdges.length,
      })
    }
    // Fall back to first match rather than returning null
    return matchingEdges[0].id
  }

  return matchingEdges[index].id
}

/**
 * Maps array of PLoT edge IDs to UI edge IDs, filtering unmappable ones.
 *
 * @param plotIds - Array of PLoT edge IDs
 * @param uiEdges - UI edges to search
 * @returns Mapping result with mapped and unmapped IDs
 */
export function mapEdgeIds(plotIds: string[], uiEdges: Edge[]): IdMappingResult {
  const mapped: string[] = []
  const unmapped: string[] = []

  for (const plotId of plotIds) {
    const uiId = mapPloTEdgeId(plotId, uiEdges)
    if (uiId) {
      mapped.push(uiId)
    } else {
      unmapped.push(plotId)
    }
  }

  if (import.meta.env.DEV && unmapped.length > 0) {
    console.warn('[IdMapping] Could not map edge IDs:', unmapped)
  }

  return { mapped, unmapped }
}

// =============================================================================
// Node ID Mapping
// =============================================================================

/**
 * Verify node IDs exist in UI and return valid ones.
 * Node IDs should be stable between PLoT and UI, but we verify anyway.
 *
 * @param nodeIds - Array of node IDs to verify
 * @param uiNodes - UI nodes to search
 * @returns Mapping result with valid and invalid IDs
 */
export function verifyNodeIds(nodeIds: string[], uiNodes: Node[]): IdMappingResult {
  const nodeIdSet = new Set(uiNodes.map(n => n.id))
  const mapped: string[] = []
  const unmapped: string[] = []

  for (const nodeId of nodeIds) {
    if (nodeIdSet.has(nodeId)) {
      mapped.push(nodeId)
    } else {
      unmapped.push(nodeId)
    }
  }

  if (import.meta.env.DEV && unmapped.length > 0) {
    console.warn('[IdMapping] Node IDs not found in canvas:', unmapped)
  }

  return { mapped, unmapped }
}

// =============================================================================
// Highlight Mapping
// =============================================================================

/**
 * Maps highlight IDs based on type, converting PLoT format to UI format.
 *
 * @param highlight - Highlight with IDs to map
 * @param uiNodes - UI nodes for verification
 * @param uiEdges - UI edges for mapping
 * @returns New highlight with mapped IDs
 */
export function mapHighlightIds(
  highlight: Highlight,
  uiNodes: Node[],
  uiEdges: Edge[]
): Highlight {
  if (highlight.type === 'node') {
    const result = verifyNodeIds(highlight.ids, uiNodes)
    return { ...highlight, ids: result.mapped }
  }

  if (highlight.type === 'edge') {
    const result = mapEdgeIds(highlight.ids, uiEdges)
    return { ...highlight, ids: result.mapped }
  }

  if (highlight.type === 'path') {
    // Path may contain both nodes and edges
    // Try to map as edges first (since edge IDs are more likely to need mapping)
    const edgeResult = mapEdgeIds(highlight.ids, uiEdges)

    // For IDs that didn't map as edges, try as nodes
    const nodeResult = verifyNodeIds(edgeResult.unmapped, uiNodes)

    // Combine successfully mapped IDs
    return {
      ...highlight,
      ids: [...edgeResult.mapped, ...nodeResult.mapped],
    }
  }

  // Unknown type - return as-is
  return highlight
}

/**
 * Map multiple highlights, filtering out those with no valid IDs.
 *
 * @param highlights - Array of highlights to map
 * @param uiNodes - UI nodes for verification
 * @param uiEdges - UI edges for mapping
 * @returns Mapped highlights (only those with at least one valid ID)
 */
export function mapHighlights(
  highlights: Highlight[],
  uiNodes: Node[],
  uiEdges: Edge[]
): Highlight[] {
  return highlights
    .map(h => mapHighlightIds(h, uiNodes, uiEdges))
    .filter(h => h.ids.length > 0)
}

// =============================================================================
// PLoT Edge ID Generation
// =============================================================================

/**
 * Generate PLoT edge ID from UI edge.
 * Useful when storing plot_id on UI edges for reliable mapping.
 *
 * @param edge - UI edge
 * @param uiEdges - All UI edges (to determine index for parallel edges)
 * @returns PLoT format edge ID
 */
export function generatePloTEdgeId(edge: Edge, uiEdges: Edge[]): string {
  // Find all edges with same source/target, sorted by ID
  const matchingEdges = uiEdges
    .filter(e => e.source === edge.source && e.target === edge.target)
    .sort((a, b) => a.id.localeCompare(b.id))

  // Find this edge's index
  const index = matchingEdges.findIndex(e => e.id === edge.id)

  return `${edge.source}::${edge.target}::${index >= 0 ? index : 0}`
}

/**
 * Store PLoT edge IDs on all UI edges for reliable mapping.
 * Call this after edges are modified.
 *
 * @param edges - UI edges to annotate
 * @returns New edges with plot_id stored in data
 */
export function annotateEdgesWithPloTIds(edges: Edge[]): Edge[] {
  return edges.map(edge => ({
    ...edge,
    data: {
      ...(edge.data || {}),
      plot_id: generatePloTEdgeId(edge, edges),
    },
  }))
}

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Check if an ID looks like a PLoT edge ID format
 */
export function isPloTEdgeIdFormat(id: string): boolean {
  return id.includes('::')
}

/**
 * Parse PLoT edge ID into components
 */
export function parsePloTEdgeId(plotEdgeId: string): {
  from: string
  to: string
  index: number
} | null {
  const parts = plotEdgeId.split('::')
  if (parts.length < 2) {
    return null
  }

  return {
    from: parts[0],
    to: parts[1],
    index: parts[2] ? parseInt(parts[2], 10) : 0,
  }
}

/**
 * Create a bidirectional mapping between PLoT and UI edge IDs.
 * Useful for bulk operations or caching.
 *
 * @param uiEdges - UI edges
 * @returns Maps for both directions
 */
export function createEdgeIdMaps(uiEdges: Edge[]): {
  plotToUi: Map<string, string>
  uiToPlot: Map<string, string>
} {
  const plotToUi = new Map<string, string>()
  const uiToPlot = new Map<string, string>()

  for (const edge of uiEdges) {
    const plotId = generatePloTEdgeId(edge, uiEdges)
    plotToUi.set(plotId, edge.id)
    uiToPlot.set(edge.id, plotId)

    // Also check stored plot_id
    const storedPlotId = (edge.data as any)?.plot_id
    if (storedPlotId && storedPlotId !== plotId) {
      plotToUi.set(storedPlotId, edge.id)
    }
  }

  return { plotToUi, uiToPlot }
}
