[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"
pinned_version = "6"

[plugins.inputs]

[build]
publish = "/Users/paulslee/Documents/GitHub/DecisionGuideAI/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build:ci && echo '{\"commit\":\"'$(git rev-parse HEAD)'\",\"short\":\"'$(git rev-parse --short HEAD)'\",\"branch\":\"'$(git rev-parse --abbrev-ref HEAD)'\",\"timestamp\":\"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'\"}' > dist/version.json"

[build.environment]
NODE_VERSION = "20"
VITE_PLC_LAB = "1"
VITE_FEATURE_PLOT_USES_PLC_CANVAS = "1"
VITE_POC_ONLY = "0"
VITE_AUTH_MODE = "guest"
VITE_EDGE_GATEWAY_URL = "/engine"
VITE_DISABLE_OPENAI = "1"
VITE_FORCE_ENGINE = "1"
VITE_FEATURE_SSE = "1"
VITE_FEATURE_SCENARIO_SANDBOX = "1"
VITE_FEATURE_SANDBOX_DECISION_CTA = "1"
VITE_FEATURE_SANDBOX_MAPPING = "1"
VITE_FEATURE_SANDBOX_PROJECTIONS = "1"
VITE_FEATURE_SANDBOX_REALTIME = "1"
VITE_FEATURE_SANDBOX_STRATEGY_BRIDGE = "1"
VITE_FEATURE_SANDBOX_TRIGGERS_BASIC = "1"
VITE_FEATURE_SANDBOX_VOTING = "1"
VITE_FEATURE_WHITEBOARD = "1"
SECRETS_SCAN_ENABLED = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
Access-Control-Allow-Headers = "Content-Type, Authorization, x-client-info, apikey, Range, x-client-version"
Access-Control-Expose-Headers = "Content-Range, Range"
Access-Control-Max-Age = "86400"
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"

[[redirects]]
from = "/engine/*"
to = "https://plot-lite-service.onrender.com/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/poc"
to = "/poc.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/fixtures/*"
to = "/fixtures/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]