create role anon nologin; create role authenticated nologin; create role service_role nologin;
create schema auth; grant usage on schema auth to anon, authenticated, service_role;
grant usage on schema public to anon, authenticated, service_role;
create table auth.users(id uuid primary key, email text);
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims', true),''),'{}')::jsonb $$;
create function auth.uid() returns uuid language sql stable as $$ select nullif(auth.jwt()->>'sub','')::uuid $$;
grant execute on function auth.uid(), auth.jwt() to anon, authenticated, service_role;
create table organisations(id uuid primary key, name text, owner_id uuid, slug text, plan_type text);
create table organisation_members(organisation_id uuid not null, user_id uuid not null, role text, unique(organisation_id,user_id));
create table teams(id uuid primary key, name text, description text, created_by uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create table team_members(id uuid primary key default gen_random_uuid(), team_id uuid, user_id uuid, role text, decision_role text, joined_at timestamptz default now(), unique(team_id,user_id));
create table invitations(id uuid primary key, email text not null, invited_at timestamptz not null default now(), status text not null, invited_by uuid, team_id uuid, role text, decision_role text, organisation_id uuid);
create table invitation_logs(id uuid primary key default gen_random_uuid(), invitation_id uuid, status text, details jsonb, created_at timestamptz);
create table canvases(id uuid primary key, user_id uuid, organisation_id uuid);
create table canvas_permissions(canvas_id uuid, user_id uuid, permission_type text, granted_by uuid, unique(canvas_id,user_id));
-- real helper used by manage_team_member
create function check_team_admin(team_uuid uuid) returns boolean language plpgsql security definer set search_path=public as $$
BEGIN RETURN EXISTS (SELECT 1 FROM teams WHERE id = team_uuid AND created_by = auth.uid()) OR EXISTS (SELECT 1 FROM team_members WHERE team_id = team_uuid AND user_id = auth.uid() AND role = 'admin'); END; $$;
create function send_email_with_template(p_to text, p_subject text, p_template_name text, p_template_data jsonb default '{}') returns jsonb language sql security definer as $$ select '{"success":true,"message_id":"m1"}'::jsonb $$;
create function can_create_organization(user_id_param uuid, plan_type_param text) returns boolean language sql security definer as $$ select true $$;
create function public.add_team_member(uuid,uuid,text,text) returns boolean language sql security definer as $$ select true $$;
create function public.check_organisation_slug_exists(text) returns boolean language sql security definer as $$ select true $$;
create function public.check_pending_invitations(text) returns boolean language sql security definer as $$ select true $$;
create function public.check_team_admin_access(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.check_team_member(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.check_team_member_access(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.check_team_permission(uuid,text) returns boolean language sql security definer as $$ select true $$;
create function public.check_team_size_limit(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.create_invite_link(uuid,integer) returns boolean language sql security definer as $$ select true $$;
create function public.get_invitation_status(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.get_organisation_details(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.get_organisation_invitations(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.get_organisation_members(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.get_organisation_teams(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.get_team_details(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.get_team_invitations(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.get_team_members(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.get_user_organisations() returns boolean language sql security definer as $$ select true $$;
create function public.get_user_teams() returns boolean language sql security definer as $$ select true $$;
create function public.has_collaborator_access(uuid,uuid) returns boolean language sql security definer as $$ select true $$;
create function public.has_team_permission(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.invite_user_to_organization_or_team(text,uuid,uuid,text,text) returns boolean language sql security definer as $$ select true $$;
create function public.is_team_admin(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.is_team_admin(uuid,uuid) returns boolean language sql security definer as $$ select true $$;
create function public.is_team_member(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.is_team_member(uuid,uuid) returns boolean language sql security definer as $$ select true $$;
create function public.manage_team_invitation(uuid,text,text) returns boolean language sql security definer as $$ select true $$;
create function public.manage_team_invite(uuid,text,text,text) returns boolean language sql security definer as $$ select true $$;
create function public.manage_team_invite(uuid,text,uuid,text) returns boolean language sql security definer as $$ select true $$;
create function public.manage_team_invite(uuid,text,uuid,text,text) returns boolean language sql security definer as $$ select true $$;
create function public.remove_organization_member(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.remove_team_member(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.request_organization_access(text,text,text,text) returns boolean language sql security definer as $$ select true $$;
create function public.resend_organisation_invitation(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.resend_team_invitation(uuid) returns boolean language sql security definer as $$ select true $$;
create function public.send_team_invitation_email(uuid,text,text,text,text,text) returns boolean language sql security definer as $$ select true $$;
create function public.test_email_sending(text) returns boolean language sql security definer as $$ select true $$;
create function public.update_organization_member_role(uuid,text) returns boolean language sql security definer as $$ select true $$;
create function public.update_team_member_role(uuid,text) returns boolean language sql security definer as $$ select true $$;
