[build]
  command = "npm run build:poc && echo '{\"commit\":\"'$(git rev-parse HEAD)'\",\"short\":\"'$(git rev-parse --short HEAD)'\",\"branch\":\"'$(git rev-parse --abbrev-ref HEAD)'\",\"timestamp\":\"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'\"}' > dist/version.json"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_POC_ONLY = "1"
  VITE_AUTH_MODE = "guest"
  VITE_EDGE_GATEWAY_URL = "/engine"
  VITE_DISABLE_OPENAI = "1"
  VITE_FORCE_ENGINE = "1"
  SECRETS_SCAN_ENABLED = "false"

# POC: redirects live in /public/_redirects only
