/**
 * ASK_TEMPLATES — every ask hands judgement back, not just `option`.
 *
 * ⭐ WHAT THIS PINS, AND WHY IT IS A PROPERTY TEST RATHER THAN A STRING PIN.
 * Seven of the nine asks used to ask the product to EXPLAIN ("Tell me about…",
 * "Explain the relationship…") or to DECIDE ("What drives {label} the most?",
 * "How important is {label}?"). `option` alone already carried the ruling —
 * its own comment states it: *"the ask ends by handing judgement back to the
 * user rather than substituting for it. Humans remain the authors."* This file
 * extends that discipline to the whole record.
 *
 * Pinning the replacement sentences verbatim would stop the NEXT edit being
 * reworded; it would not stop the defect being re-introduced under new words.
 * So these assert the PROPERTIES the ruling is about, and any reword that keeps
 * them passes.
 *
 * ⚠ DERIVED FROM THE RECORD, NOT MIRRORED FROM IT (trap 12). Every case is
 * generated by iterating `ASK_TEMPLATES`, so a key added later is covered with
 * no edit here, and a key removed REDs the completeness test rather than
 * silently shrinking the table. There is no hand-maintained list of keys or of
 * key→placeholder pairs anywhere in this file.
 *
 * ⚠ EVERY LEXICON HAS A POSITIVE CONTROL (trap 13). An "absent from this
 * string" assertion is vacuous unless the pattern is shown to SEE the language
 * it bans, so each guard is first fed the exact sentences that used to ship and
 * required to hit them. Without that, a typo in a pattern leaves the whole file
 * green while banning nothing.
 *
 * ⚠ THIS FILE DELIBERATELY DOES NOT RE-COVER `option`'s RENDER PATH.
 * `shared/__tests__/optionAskPromptNoRanking.spec.tsx` already pins the ranking
 * lexicon and the live `inspector-quick-ask` click for that one panel. This is
 * the record-wide twin: the property over all nine keys, at the register.
 *
 * ⛔ KNOWN GAP, PINNED IN BOTH DIRECTIONS. `factor-external` as briefed carries
 * no first-person marker at all — it names what the model assumed and exposes
 * the sensitivity, but it does not end by handing judgement back. That is a real
 * shortfall against the principle, not a wording preference, so it is recorded
 * here as an EXACT set rather than hidden by loosening the guard: the test REDs
 * if the set grows (a second ask stops handing judgement back) AND if it shrinks
 * (the gap was closed and the pin is now stale). See trap 22f — a gap recorded
 * in the suite is honest; a gap invisible to it is how it recurs.
 */

import { describe, it, expect } from 'vitest'

import { ASK_TEMPLATES, resolveAskTemplate } from '../inspectorStrings'

/**
 * The oracle openings this change removes. Each of these asks the product to
 * explain, to rate, or to decide — the shapes that substitute the model's
 * judgement for the user's.
 */
const ORACLE_OPENING = /^(Tell me|Explain|How can we|What are the key|How important)/i

/**
 * Language that asks the product to rank or to name a winner. Paul's standing
 * ruling: the product is not entitled to state that conclusion, so an affordance
 * must not ask for it on the user's behalf.
 */
const RANKING_LEXICON =
  /\bthe most\b|\bmost important\b|\bcompar(?:e|es|ed|ing|ison)\b|\branks?\b|\branking\b|\bbetter than\b|\bbest\b/i

/**
 * First-person-judgement markers — the ask addresses the user as the author and
 * the decision-maker.
 *
 * ⚠ SCOPE NOTE, DELIBERATE IN BOTH DIRECTIONS. `me` is included: "what has it
 * left to me to weigh?" hands judgement back as plainly as "mine to judge", and
 * excluding it would have manufactured a false gap against `decision`. The
 * collective `we`/`us`/`our` is EXCLUDED: "How can we reduce {label}?" is the
 * product-and-user collective and was one of the sentences this change removes,
 * so counting it would let the defect satisfy the guard. The sibling
 * `optionAskPromptNoRanking.spec.tsx` uses the wider set for a different job
 * (any address to the user at all); this one is about the user's OWN judgement.
 */
const FIRST_PERSON_JUDGEMENT = /\b(?:mine|my|me)\b|\bI\b/

/**
 * ⛔ THE LOOPHOLE `me` OPENS, CLOSED EXPLICITLY. Measured on the pristine record
 * before this change: *"Tell me about the chances of achieving {label}"* SATISFIES
 * `FIRST_PERSON_JUDGEMENT`, because "Tell me" contains `me`. The oracle form that
 * hands judgement furthest away is the one that slips the judgement guard. The
 * opening guard catches it only at position 0, so "Show me which of these…" would
 * pass both. This bans the request-to-the-product imperative anywhere in the
 * sentence — the exact shape that exploits the marker, and no parsing cleverness.
 */
const ORACLE_REQUEST_ANYWHERE = /\b(?:tell|show|give)\s+me\b/i

/** The asks that are NOT yet holding the property. Exact, and pinned as exact. */
const KNOWN_NO_JUDGEMENT_CLAUSE = ['factor-external'] as const

/** Derived, never hand-listed: the placeholders an ask for `key` must carry. */
function requiredPlaceholders(key: string): string[] {
  return key === 'edge' ? ['{sourceLabel}', '{targetLabel}'] : ['{label}']
}

const ENTRIES = Object.entries(ASK_TEMPLATES)

// ─────────────────────────────────────────────────────────────────────
// The instrument itself — every guard must be shown able to fire
// ─────────────────────────────────────────────────────────────────────

describe('the instrument itself', () => {
  it('POSITIVE CONTROL — the oracle pattern sees all five openings that used to ship', () => {
    const shipped = [
      'Tell me about the chances of achieving {label}',
      'Explain the relationship between {sourceLabel} and {targetLabel}',
      'How can we reduce {label}?',
      'What are the key trade-offs in {label}?',
      'How important is {label} to the outcome?',
    ]
    for (const sentence of shipped) {
      expect(ORACLE_OPENING.test(sentence), sentence).toBe(true)
    }
  })

  it('POSITIVE CONTROL — the ranking lexicon sees the decide-for-me sentences', () => {
    expect(RANKING_LEXICON.test('What drives {label} the most?')).toBe(true)
    expect(RANKING_LEXICON.test('Which is the best option?')).toBe(true)
    expect(RANKING_LEXICON.test('How does this compare to the others?')).toBe(true)
    expect(RANKING_LEXICON.test('Is this better than the alternative?')).toBe(true)
    expect(RANKING_LEXICON.test('Rank these by impact')).toBe(true)
    expect(RANKING_LEXICON.test('What is most important here?')).toBe(true)
  })

  it('POSITIVE CONTROL — the request-to-the-product guard sees the shape that slips the marker', () => {
    // Both of these satisfy FIRST_PERSON_JUDGEMENT via `me`, which is exactly
    // why this second guard exists. Asserted together so the pairing is visible.
    expect(FIRST_PERSON_JUDGEMENT.test('Tell me about the chances of achieving {label}')).toBe(true)
    expect(ORACLE_REQUEST_ANYWHERE.test('Tell me about the chances of achieving {label}')).toBe(true)
    expect(ORACLE_REQUEST_ANYWHERE.test('Show me which of these matters')).toBe(true)
    expect(ORACLE_REQUEST_ANYWHERE.test('Give me the answer')).toBe(true)
    expect(ORACLE_REQUEST_ANYWHERE.test('what has it left to me to weigh?')).toBe(false)
  })

  it('POSITIVE CONTROL — the judgement pattern hits a genuine hand-back', () => {
    expect(FIRST_PERSON_JUDGEMENT.test('Say which of those assumptions are mine to judge.')).toBe(true)
    expect(FIRST_PERSON_JUDGEMENT.test('what has it left to me to weigh?')).toBe(true)
    expect(FIRST_PERSON_JUDGEMENT.test('where would my own knowledge change the picture?')).toBe(true)
    expect(FIRST_PERSON_JUDGEMENT.test('If I moved this, what changes?')).toBe(true)
  })

  it('NEGATIVE CONTROL — the judgement pattern can fail, and the collective does not satisfy it', () => {
    expect(FIRST_PERSON_JUDGEMENT.test('What drives this the most?')).toBe(false)
    expect(FIRST_PERSON_JUDGEMENT.test('How can we reduce this?')).toBe(false)
    expect(FIRST_PERSON_JUDGEMENT.test('How sensitive are the results to this?')).toBe(false)
  })

  it('PRECONDITION — the record is non-empty, so the generated tables are not vacuous', () => {
    expect(ENTRIES.length).toBeGreaterThan(0)
  })
})

// ─────────────────────────────────────────────────────────────────────
// Completeness — a key silently dropped must RED
// ─────────────────────────────────────────────────────────────────────

describe('ASK_TEMPLATES · the record is complete', () => {
  it('carries exactly the nine element kinds the inspector can ask about', () => {
    expect(Object.keys(ASK_TEMPLATES).sort()).toEqual(
      [
        'decision',
        'edge',
        'factor-controllable',
        'factor-external',
        'factor-observable',
        'goal',
        'option',
        'outcome',
        'risk',
      ].sort(),
    )
  })

  it('the known-gap pin names only keys that exist', () => {
    for (const key of KNOWN_NO_JUDGEMENT_CLAUSE) {
      expect(Object.keys(ASK_TEMPLATES)).toContain(key)
    }
  })
})

// ─────────────────────────────────────────────────────────────────────
// The property, per key, bound by identity
// ─────────────────────────────────────────────────────────────────────

describe('ASK_TEMPLATES · no ask asks the product to explain or to decide', () => {
  it.each(ENTRIES)('%s does not open with an oracle form', (key, template) => {
    expect(ORACLE_OPENING.test(template), `${key}: ${template}`).toBe(false)
  })

  it.each(ENTRIES)('%s does not ask the product to rank', (key, template) => {
    expect(RANKING_LEXICON.test(template), `${key}: ${template}`).toBe(false)
  })

  it.each(ENTRIES)('%s does not ask the product to hand the answer over', (key, template) => {
    expect(ORACLE_REQUEST_ANYWHERE.test(template), `${key}: ${template}`).toBe(false)
  })
})

describe('ASK_TEMPLATES · every ask hands judgement back to the user', () => {
  it.each(ENTRIES)('%s addresses the user as the one who judges', (key, template) => {
    if ((KNOWN_NO_JUDGEMENT_CLAUSE as readonly string[]).includes(key)) {
      // Pinned gap, asserted in the failing direction so closing it REDs here
      // and forces the pin to be removed rather than left to rot.
      expect(FIRST_PERSON_JUDGEMENT.test(template), `${key} is pinned as a KNOWN GAP but now hands judgement back — remove it from KNOWN_NO_JUDGEMENT_CLAUSE: ${template}`).toBe(false)
      return
    }
    expect(FIRST_PERSON_JUDGEMENT.test(template), `${key}: ${template}`).toBe(true)
  })
})

describe('ASK_TEMPLATES · every ask still names the element it is about', () => {
  it.each(ENTRIES)('%s carries the placeholders its key requires', (key, template) => {
    for (const placeholder of requiredPlaceholders(key)) {
      expect(template, `${key}: ${template}`).toContain(placeholder)
    }
  })

  it.each(ENTRIES)('%s resolves with real labels substituted in and no placeholder left behind', (key, template) => {
    const resolved = resolveAskTemplate(key, {
      label: 'Pilot in Germany',
      sourceLabel: 'Capacity',
      targetLabel: 'On-time Delivery',
    })
    expect(resolved, `${key} resolved to null: ${template}`).not.toBeNull()
    expect(resolved as string, `${key}: ${template}`).not.toContain('{')
    for (const expected of requiredPlaceholders(key) as string[]) {
      const value =
        expected === '{sourceLabel}'
          ? 'Capacity'
          : expected === '{targetLabel}'
            ? 'On-time Delivery'
            : 'Pilot in Germany'
      expect(resolved as string, `${key}: ${template}`).toContain(value)
    }
  })
})
