/**
 * Scenario Persistence Service — Olumi Scenario Schema v2.0
 *
 * Pure async functions wrapping Supabase RPCs and direct queries.
 * No React dependencies. Nothing else in the app calls Supabase
 * for scenario data directly — all access goes through this module.
 *
 * Every function checks `.error` on the Supabase response and throws
 * a typed `ScenarioPersistenceError`. Errors are never swallowed.
 *
 * `eventId` parameters are generated by the **caller** via
 * `crypto.randomUUID()`, never inside service functions. This keeps
 * idempotency control with the caller.
 */

import { supabase } from '../lib/supabase'
import { clearSuppressedScenarioId } from './threadService'
import type {
  ScenarioRow,
  ScenarioListItem,
  ScenarioStage,
  SharedBriefRow,
} from '../types/scenario'
import { ScenarioPersistenceError } from '../types/scenario'

// ---------------------------------------------------------------------------
// Guard: reject non-UUID user IDs (prevents FK violations in guest mode)
// ---------------------------------------------------------------------------

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

function assertValidUserId(userId: string): void {
  if (!UUID_RE.test(userId)) {
    throw new ScenarioPersistenceError(
      'Supabase persistence requires an authenticated user',
      'INVALID_USER_ID',
    )
  }
}

// ---------------------------------------------------------------------------
// 1. createScenario
// ---------------------------------------------------------------------------

export async function createScenario(
  userId: string,
  eventId: string,
  title?: string,
): Promise<ScenarioRow> {
  assertValidUserId(userId)

  const { data, error } = await supabase
    .from('scenarios')
    .insert({
      user_id: userId,
      title: title ?? null,
      stage: 'frame',
      analysis_status: 'none',
    })
    .select()
    .single()

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to create scenario: ${error.message}`,
      'CREATE_FAILED',
      error,
    )
  }

  // Append scenario_created event
  const { error: eventError } = await supabase.rpc('append_scenario_event', {
    p_scenario_id: data.id,
    p_event_id: eventId,
    p_event_type: 'scenario_created',
    p_details: {},
    p_hashes: null,
    p_turn_id: null,
  })

  if (eventError) {
    throw new ScenarioPersistenceError(
      `Failed to log scenario_created event: ${eventError.message}`,
      'EVENT_APPEND_FAILED',
      eventError,
    )
  }

  // Clear turn insert suppression so conversation turns can persist for this scenario
  clearSuppressedScenarioId(data.id)

  return data as ScenarioRow
}

// ---------------------------------------------------------------------------
// 2. listScenarios
// ---------------------------------------------------------------------------

export async function listScenarios(
  userId: string,
): Promise<ScenarioListItem[]> {
  assertValidUserId(userId)

  const { data, error } = await supabase
    .from('scenarios')
    .select('id, title, stage, analysis_status, updated_at, created_at, events, is_pinned, is_archived')
    .eq('user_id', userId)
    .order('is_pinned', { ascending: false })
    .order('updated_at', { ascending: false })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to list scenarios: ${error.message}`,
      'LIST_FAILED',
      error,
    )
  }

  return (data ?? []) as ScenarioListItem[]
}

// ---------------------------------------------------------------------------
// 3. loadScenario
// ---------------------------------------------------------------------------

export async function loadScenario(
  scenarioId: string,
): Promise<ScenarioRow | null> {
  const { data, error } = await supabase
    .from('scenarios')
    .select('*')
    .eq('id', scenarioId)
    .single()

  if (error) {
    // PGRST116 = "no rows returned" — not found, not an error
    if (error.code === 'PGRST116') return null
    throw new ScenarioPersistenceError(
      `Failed to load scenario: ${error.message}`,
      'LOAD_FAILED',
      error,
    )
  }

  return data as ScenarioRow
}

// ---------------------------------------------------------------------------
// 4. saveGraph (direct UPDATE, no event — §6.1)
// ---------------------------------------------------------------------------

export async function saveGraph(
  scenarioId: string,
  graph: unknown,
): Promise<void> {
  const { error } = await supabase
    .from('scenarios')
    .update({ graph })
    .eq('id', scenarioId)

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to save graph: ${error.message}`,
      'SAVE_GRAPH_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 5. saveFraming (direct UPDATE, no event — §6.1)
// ---------------------------------------------------------------------------

export async function saveFraming(
  scenarioId: string,
  framing: unknown,
): Promise<void> {
  const { error } = await supabase
    .from('scenarios')
    .update({ framing })
    .eq('id', scenarioId)

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to save framing: ${error.message}`,
      'SAVE_FRAMING_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 5b. resetAnalysisStatus (direct UPDATE — §7 interrupted analysis recovery)
// ---------------------------------------------------------------------------

export async function resetAnalysisStatus(
  scenarioId: string,
): Promise<void> {
  const { error } = await supabase
    .from('scenarios')
    .update({ analysis_status: 'none', analysis_error: null })
    .eq('id', scenarioId)

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to reset analysis status: ${error.message}`,
      'RESET_ANALYSIS_STATUS_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 5c. setAnalysisRunning (direct UPDATE — marks analysis as in-progress)
// ---------------------------------------------------------------------------

export async function setAnalysisRunning(
  scenarioId: string,
): Promise<void> {
  const { error } = await supabase
    .from('scenarios')
    .update({ analysis_status: 'running', analysis_error: null })
    .eq('id', scenarioId)

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to set analysis running: ${error.message}`,
      'SET_RUNNING_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 6. saveTitle (direct UPDATE, no event)
// ---------------------------------------------------------------------------

export async function saveTitle(
  scenarioId: string,
  title: string,
): Promise<void> {
  const { error } = await supabase
    .from('scenarios')
    .update({ title })
    .eq('id', scenarioId)

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to save title: ${error.message}`,
      'SAVE_TITLE_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 7. storeAnalysis (store_analysis_and_log RPC — §4.3)
// ---------------------------------------------------------------------------

export async function storeAnalysis(
  scenarioId: string,
  analysis: unknown,
  graphHash: string,
  /**
   * T2b: null when the engine did not echo a usable seed. The RPC param
   * `p_seed_used INTEGER` has no NOT NULL and no default, and
   * `analysis_provenance` is JSONB, so a null lands as JSON `null` — an
   * honest "unknown" that hydrateAnalysis reads back as null.
   */
  seedUsed: number | null,
  responseHash: string,
  eventId: string,
  details?: Record<string, unknown>,
  turnId?: string,
): Promise<void> {
  const { error } = await supabase.rpc('store_analysis_and_log', {
    p_scenario_id: scenarioId,
    p_analysis: analysis,
    p_graph_hash: graphHash,
    p_seed_used: seedUsed,
    p_response_hash: responseHash,
    p_event_id: eventId,
    p_details: details ?? {},
    p_turn_id: turnId ?? null,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to store analysis: ${error.message}`,
      'STORE_ANALYSIS_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 8. storeAnalysisFailure (store_analysis_failure RPC — §4.4)
// ---------------------------------------------------------------------------

export async function storeAnalysisFailure(
  scenarioId: string,
  errorPayload: { code: string; message: string },
  eventId: string,
  turnId?: string,
): Promise<void> {
  const { error } = await supabase.rpc('store_analysis_failure', {
    p_scenario_id: scenarioId,
    p_error: errorPayload,
    p_event_id: eventId,
    p_turn_id: turnId ?? null,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to store analysis failure: ${error.message}`,
      'STORE_ANALYSIS_FAILURE_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 9. storeBrief (store_brief_and_log RPC — §4.5)
// ---------------------------------------------------------------------------

export async function storeBrief(
  scenarioId: string,
  brief: unknown,
  eventId: string,
  turnId?: string,
): Promise<void> {
  const { error } = await supabase.rpc('store_brief_and_log', {
    p_scenario_id: scenarioId,
    p_brief: brief,
    p_event_id: eventId,
    p_turn_id: turnId ?? null,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to store brief: ${error.message}`,
      'STORE_BRIEF_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 10. setStage (set_stage_and_log RPC — §4.6)
// ---------------------------------------------------------------------------

export async function setStage(
  scenarioId: string,
  newStage: ScenarioStage,
  eventId: string,
  turnId?: string,
): Promise<void> {
  const { error } = await supabase.rpc('set_stage_and_log', {
    p_scenario_id: scenarioId,
    p_new_stage: newStage,
    p_event_id: eventId,
    p_turn_id: turnId ?? null,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to set stage: ${error.message}`,
      'SET_STAGE_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 11. applyPatchAndLog (apply_patch_and_log RPC — §4.2)
// ---------------------------------------------------------------------------

export async function applyPatchAndLog(
  scenarioId: string,
  graph: unknown,
  eventId: string,
  eventType: 'patch_accepted' | 'patch_dismissed' | 'patch_rejected',
  details?: Record<string, unknown>,
  hashes?: Record<string, string>,
  turnId?: string,
): Promise<void> {
  const { error } = await supabase.rpc('apply_patch_and_log', {
    p_scenario_id: scenarioId,
    p_graph: graph,
    p_event_id: eventId,
    p_event_type: eventType,
    p_details: details ?? {},
    p_hashes: hashes ?? null,
    p_turn_id: turnId ?? null,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to apply patch: ${error.message}`,
      'APPLY_PATCH_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 12. appendEvent (append_scenario_event RPC — §4.1)
// ---------------------------------------------------------------------------

export async function appendEvent(
  scenarioId: string,
  eventId: string,
  eventType: string,
  details?: Record<string, unknown>,
  hashes?: Record<string, string>,
  turnId?: string,
): Promise<void> {
  const { error } = await supabase.rpc('append_scenario_event', {
    p_scenario_id: scenarioId,
    p_event_id: eventId,
    p_event_type: eventType,
    p_details: details ?? {},
    p_hashes: hashes ?? null,
    p_turn_id: turnId ?? null,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to append event: ${error.message}`,
      'APPEND_EVENT_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 13. deleteScenario (cascades to shared_briefs via FK)
// ---------------------------------------------------------------------------

export async function deleteScenario(scenarioId: string): Promise<void> {
  const { error } = await supabase
    .from('scenarios')
    .delete()
    .eq('id', scenarioId)

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to delete scenario: ${error.message}`,
      'DELETE_FAILED',
      error,
    )
  }
}

// ---------------------------------------------------------------------------
// 14. createSharedBrief (create_shared_brief RPC — §4.7)
//     Slug is generated server-side. Returns { id, slug }.
// ---------------------------------------------------------------------------

export async function createSharedBrief(
  scenarioId: string,
): Promise<{ id: string; slug: string }> {
  const { data, error } = await supabase.rpc('create_shared_brief', {
    p_scenario_id: scenarioId,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to create shared brief: ${error.message}`,
      'CREATE_SHARED_BRIEF_FAILED',
      error,
    )
  }

  return data as { id: string; slug: string }
}

// ---------------------------------------------------------------------------
// 15. getSharedBriefBySlug (get_shared_brief_by_slug RPC — §4.8)
//     No auth required — uses anon client.
// ---------------------------------------------------------------------------

export async function getSharedBriefBySlug(
  slug: string,
): Promise<SharedBriefRow | null> {
  const { data, error } = await supabase.rpc('get_shared_brief_by_slug', {
    p_slug: slug,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to fetch shared brief: ${error.message}`,
      'GET_SHARED_BRIEF_FAILED',
      error,
    )
  }

  return (data as SharedBriefRow) ?? null
}

// ---------------------------------------------------------------------------
// 16. Hub operations — pin, archive, duplicate
// ---------------------------------------------------------------------------

export async function pinScenario(
  scenarioId: string,
  isPinned: boolean,
): Promise<void> {
  const { error } = await supabase
    .from('scenarios')
    .update({ is_pinned: isPinned })
    .eq('id', scenarioId)

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to ${isPinned ? 'pin' : 'unpin'} scenario: ${error.message}`,
      'PIN_FAILED',
      error,
    )
  }
}

export async function archiveScenario(
  scenarioId: string,
  isArchived: boolean,
): Promise<void> {
  const { error } = await supabase
    .from('scenarios')
    .update({ is_archived: isArchived })
    .eq('id', scenarioId)

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to ${isArchived ? 'archive' : 'unarchive'} scenario: ${error.message}`,
      'ARCHIVE_FAILED',
      error,
    )
  }
}

export async function duplicateScenario(
  scenarioId: string,
): Promise<string> {
  const { data, error } = await supabase.rpc('duplicate_scenario', {
    p_scenario_id: scenarioId,
  })

  if (error) {
    throw new ScenarioPersistenceError(
      `Failed to duplicate scenario: ${error.message}`,
      'DUPLICATE_FAILED',
      error,
    )
  }

  return data as string
}
