/**
 * friendlyOperation.ts
 *
 * Converts raw PatchOperation data into human-readable strings for display
 * in the AI conversation panel. Raw node/edge IDs must NEVER appear in
 * rendered UI — this module provides the guaranteed fallback chain.
 *
 * Label resolution priority (per element):
 *   1. proposalItem.elementLabel (CEE-provided label on the payload)
 *   2. op.data.label             (for add_node, where label is in the data)
 *   3. relatedElements lookup    (CEE-provided related_elements array)
 *   4. nodeLabels / edgeEndpoints (memoised canvas store read, built per render)
 *   5. GENERIC_BY_OP fallback    (human text — never the raw ID)
 */

import { FIELD_LABELS } from '../adapters/modelCardAdapter'
import type { PatchOperation, ProposalReviewItem, RelatedElementRef } from './types'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Regex for detecting raw element IDs that must never reach rendered UI.
 * Covers BOTH id-naming schemes used across the codebase (kept in sync with
 * olumi-assistants-service/src/orchestrator/patch-summary.ts:ENTITY_ID_LEAK_RE):
 *
 *   1. Short prefixes (envelope / insight convention):
 *        fac_x, opt_y, goal_z, dec_, out_, risk_, con_
 *   2. Full-word prefixes generated by deterministic action handlers
 *      (add-option.ts emits `option_hire_tech_lead`, add-factor.ts emits
 *      `factor_team_morale`, etc.):
 *        factor_, option_, decision_, outcome_, constraint_
 *
 * Without the full-word alternatives, a `factor_team_morale` string leaking
 * into a label field would slip past every tier of resolveNodeLabel and
 * render verbatim in the conversation panel.
 */
export const RAW_ID_PATTERN =
  /\b(?:opt|fac|goal|dec|out|risk|con|factor|option|decision|outcome|constraint)_[a-z0-9_]+/i

/**
 * Human-readable generic fallback when label resolution fails entirely.
 *
 * Only used when every tier of resolveNodeLabel / resolveEdgeLabel has failed.
 * Returns `"{verb} {elementType}"` where elementType is derived from the
 * target_id prefix (item 9 Path B). E.g.:
 *   - `opt_…` → "Update option", `goal_…` → "Update goal", etc.
 * Falls back to "factor" / "connection" when the prefix is unrecognised.
 *
 * Emits only word-form element types ("option", "goal", "factor", "decision",
 * "outcome", "constraint") — NEVER the raw prefix or id. This keeps the
 * RAW_ID_PATTERN security invariant intact: the output is checked by
 * friendlyOperation.spec.ts against both RAW_ID_PATTERN and
 * `not.toContain(op.target_id)`.
 */
const VERB_BY_OP: Record<PatchOperation['op'], string> = {
  add_node:    'Add',
  update_node: 'Update',
  remove_node: 'Remove',
  add_edge:    'Add',
  update_edge: 'Update',
  remove_edge: 'Remove',
}

/**
 * Map id prefix → human element-type word. Supports both short prefixes
 * (envelope convention: fac_, opt_, goal_, …) and full-word prefixes
 * (action handler convention: factor_, option_, goal_, …).
 * Order matters only for lookup; we match the full prefix, so "option_foo"
 * resolves via "option" not "opt".
 */
const ID_PREFIX_TO_TYPE: readonly { pattern: RegExp; type: string }[] = [
  { pattern: /^option_|^opt_/i,      type: 'option' },
  { pattern: /^factor_|^fac_/i,      type: 'factor' },
  { pattern: /^goal_/i,              type: 'goal' },
  { pattern: /^decision_|^dec_/i,    type: 'decision' },
  { pattern: /^outcome_|^out_/i,     type: 'outcome' },
  { pattern: /^constraint_|^con_/i,  type: 'constraint' },
  { pattern: /^risk_/i,              type: 'risk' },
]

/**
 * Derive a human element-type word from an id. Returns `fallback` (default
 * "factor" for nodes, "connection" for edges) when no prefix matches.
 *
 * Never returns any substring of the input id — only the literal type words
 * defined in ID_PREFIX_TO_TYPE, which are safe by construction.
 */
function elementTypeFromId(id: string, fallback: string): string {
  for (const { pattern, type } of ID_PREFIX_TO_TYPE) {
    if (pattern.test(id)) return type
  }
  return fallback
}

/**
 * Produce the generic fallback for an op, using element-type derivation when
 * the target_id carries a recognisable prefix. Never emits the raw id.
 */
function genericForOp(op: PatchOperation): string {
  const verb = VERB_BY_OP[op.op]
  const isEdge = op.op === 'add_edge' || op.op === 'update_edge' || op.op === 'remove_edge'
  if (isEdge) {
    // Edges don't carry a meaningful type prefix — keep "connection" verbatim.
    return `${verb} connection`
  }
  const type = elementTypeFromId(op.target_id, 'factor')
  return `${verb} ${type}`
}

/**
 * Deterministic priority order for update_node: which changed key to surface.
 * Do NOT rely on Object.keys() iteration order — it is engine-dependent.
 */
const UPDATE_FIELD_PRIORITY: readonly string[] = [
  'label',
  'kind',
  'category',
  'observedState',
  'observed_state',
  'strength',
  'strength_mean',
  'weight',
  'direction',
  'prior',
]

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Returns a display-friendly label for a raw field key.
 * Looks up FIELD_LABELS (single source of truth), falls back to camelCase
 * alias resolution then basic humanisation.
 */
export function friendlyFieldName(key: string): string {
  if (FIELD_LABELS[key]) return FIELD_LABELS[key]
  // Alias camelCase canvas keys → snake_case entries in FIELD_LABELS
  const snake = key.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase()
  if (FIELD_LABELS[snake]) return FIELD_LABELS[snake]
  return snake.replace(/_/g, ' ').replace(/^./, (c) => c.toUpperCase())
}

/**
 * Returns the first changed key from `data` according to UPDATE_FIELD_PRIORITY,
 * then any remaining keys (excluding `id`), sorted for determinism.
 *
 * Note: callers should NOT use the returned key to render a friendly suffix
 * unless `isAllowlistedFieldKey` confirms it is on the known-fields
 * allowlist — otherwise an unfamiliar payload key like `weirdInternalKey`
 * would humanise to "Weird internal key" and leak through `friendlyFieldName`
 * into the receipt. See `describeOperation`.
 */
export function firstChangedKey(
  data: Record<string, unknown> | undefined,
): string | undefined {
  if (!data) return undefined
  for (const k of UPDATE_FIELD_PRIORITY) {
    if (k in data) return k
  }
  const rest = Object.keys(data)
    .filter((k) => k !== 'id')
    .sort()
  return rest[0]
}

/**
 * Allowlist gate for receipt field suffixes.
 *
 * Two separate concepts are deliberately combined into one display
 * allowlist:
 *
 *   - `UPDATE_FIELD_PRIORITY` — ordered list used by `firstChangedKey`
 *     to *pick* which key to surface when an update payload carries
 *     several. Priority order, not a safety contract.
 *   - `FIELD_LABELS` (from modelCardAdapter) — curated table of
 *     friendly labels for receipt-renderable fields. Some entries here
 *     (e.g. `exists_probability`, `strength_std`, `baseline`,
 *     `range_min`, `range_max`) are valid update fields whose curated
 *     friendly label should appear in receipts, even though they are
 *     not part of the priority order.
 *
 * The receipt allowlist is the UNION of both — any key that has been
 * intentionally added to either deserves its curated suffix. Anything
 * else (foreign / drifted / malformed payloads) must NOT produce a
 * humanised suffix, because `friendlyFieldName` would convert arbitrary
 * camelCase like `anotherSecret` into "Another secret" — a
 * friendly-looking leak of an internal field name.
 *
 * Exported (with the legacy name `UPDATE_FIELD_PRIORITY_SET` removed)
 * so future contributors do not conflate priority order with display
 * safety.
 */
export const RECEIPT_FIELD_ALLOWLIST: ReadonlySet<string> = new Set([
  ...UPDATE_FIELD_PRIORITY,
  ...Object.keys(FIELD_LABELS),
])

export function isAllowlistedFieldKey(key: string): boolean {
  if (RECEIPT_FIELD_ALLOWLIST.has(key)) return true
  // camelCase ↔ snake_case parity: CEE may emit a camelCase variant
  // (e.g. `existsProbability`) of an otherwise-curated key.
  const snake = key.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase()
  return RECEIPT_FIELD_ALLOWLIST.has(snake)
}

// ---------------------------------------------------------------------------
// describeOperation
// ---------------------------------------------------------------------------

export interface DescribeOpDeps {
  /** CEE-provided proposal item for this operation (may carry elementLabel). */
  proposalItem?: ProposalReviewItem
  /** CEE-provided related elements array for this patch block. */
  relatedElements?: RelatedElementRef[]
  /**
   * Pre-built map of node ID → display label, built once per render from
   * the canvas store. Avoids per-operation store subscriptions.
   */
  nodeLabels: Map<string, string>
  /**
   * Pre-built map of edge ID → { from, to } source/target node IDs, built
   * once per render. Resolve display labels via nodeLabels.
   */
  edgeEndpoints: Map<string, { from: string; to: string }>
}

/** Resolve a node's display label using the 4-tier fallback chain. */
function resolveNodeLabel(
  id: string,
  deps: DescribeOpDeps,
  opData?: Record<string, unknown>,
): string {
  // 1. CEE payload label
  if (deps.proposalItem?.elementLabel && !RAW_ID_PATTERN.test(deps.proposalItem.elementLabel)) {
    return deps.proposalItem.elementLabel
  }
  // 2. label field in operation data (add_node carries it)
  if (opData?.label && typeof opData.label === 'string' && !RAW_ID_PATTERN.test(opData.label)) {
    return opData.label
  }
  // 3. related_elements lookup
  const related = deps.relatedElements?.find(
    (r) => r.node_id === id && r.label && !RAW_ID_PATTERN.test(r.label),
  )
  if (related?.label) return related.label
  // 4. memoised canvas store read
  const storeLabel = deps.nodeLabels.get(id)
  if (storeLabel && storeLabel.trim() && !RAW_ID_PATTERN.test(storeLabel)) return storeLabel
  // 5. Generic fallback — never the raw ID
  return ''
}

/** Resolve an edge's display label as "fromLabel → toLabel". */
function resolveEdgeLabel(
  id: string,
  deps: DescribeOpDeps,
  opData?: Record<string, unknown>,
): { from: string; to: string } {
  // From memoised edge endpoints
  const ep = deps.edgeEndpoints.get(id)
  if (ep) {
    return {
      from: deps.nodeLabels.get(ep.from) ?? '',
      to: deps.nodeLabels.get(ep.to) ?? '',
    }
  }
  // For add_edge, source/target are in op.data
  const src = typeof opData?.source === 'string' ? opData.source : ''
  const tgt = typeof opData?.target === 'string' ? opData.target : ''
  return {
    from: (src && deps.nodeLabels.get(src)) ?? '',
    to: (tgt && deps.nodeLabels.get(tgt)) ?? '',
  }
}

/**
 * Returns a human-readable description of a single patch operation.
 *
 * Output uses markdown `**bold**` for element names — the existing
 * ReactMarkdown / safeRichText rendering pipeline preserves it.
 *
 * Raw IDs are never emitted. When label resolution fails entirely, the
 * generic fallback derives element type from the id prefix (e.g. "Update
 * option" vs "Update goal") while emitting only the literal type word.
 */
export function describeOperation(op: PatchOperation, deps: DescribeOpDeps): string {
  const generic = genericForOp(op)

  switch (op.op) {
    case 'add_node': {
      const label = resolveNodeLabel(op.target_id, deps, op.data)
      if (!label) return generic
      const kind = typeof op.data.kind === 'string' ? op.data.kind : ''
      const kindSuffix = kind ? ` (${kind})` : ''
      return `Add **${label}**${kindSuffix}`
    }

    case 'update_node': {
      const label = resolveNodeLabel(op.target_id, deps, op.data)
      const field = firstChangedKey(op.data)
      if (!label) return generic
      // Only render a field suffix when the key is on the known-fields
      // allowlist — otherwise `friendlyFieldName` would humanise a
      // foreign / drifted key (e.g. `anotherSecret` → "Another secret")
      // into a friendly-looking leak of an internal field name.
      if (!field || !isAllowlistedFieldKey(field)) return `Update **${label}**`
      return `Update **${label}**: ${friendlyFieldName(field)}`
    }

    case 'remove_node': {
      const label = resolveNodeLabel(op.target_id, deps, op.data)
      if (!label) return generic
      return `Remove **${label}**`
    }

    case 'add_edge': {
      const { from, to } = resolveEdgeLabel(op.target_id, deps, op.data)
      if (!from && !to) return generic
      return `Connect **${from || '?'}** → **${to || '?'}**`
    }

    case 'update_edge': {
      const { from, to } = resolveEdgeLabel(op.target_id, deps, op.data)
      const field = firstChangedKey(op.data)
      if (!from && !to) return generic
      const base = `Update connection **${from || '?'}** → **${to || '?'}**`
      // Same allowlist gate as update_node — never humanise an unfamiliar
      // edge field key. Falls back to the bare connection label.
      if (!field || !isAllowlistedFieldKey(field)) return base
      return `${base}: ${friendlyFieldName(field)}`
    }

    case 'remove_edge': {
      const { from, to } = resolveEdgeLabel(op.target_id, deps, op.data)
      if (!from && !to) return generic
      return `Disconnect **${from || '?'}** → **${to || '?'}**`
    }

    default:
      return generic
  }
}
