/**
 * PipelineTab Component
 *
 * CEE internal processing stages for Debug Panel V2.
 * Shows artefact chain, pipeline stages, connectivity, M1 coaching, and M2 review.
 */

import { useState, useMemo, useCallback, CSSProperties } from 'react'
import { PipelineStage, JsonViewer } from '../components'
import type { DebugData, LlmRawData, GraphCorrection, GraphDiff, CeeOperationInfo } from '../hooks/useDebugData'
import { formatDuration } from '../utils'

// Human-readable explanations for CEE repair types
const REPAIR_TYPE_EXPLANATIONS: Record<string, string> = {
  coefficient_normalization: 'Edge strengths normalized to [-1, +1]',
  orphan_removal: 'Disconnected nodes removed from graph',
  cycle_breaking: 'Circular dependencies resolved',
  bidirectional_resolution: 'Two-way edges converted to single direction',
  missing_goal_addition: 'Goal node added to graph structure',
  invalid_edge_removal: 'Invalid connections removed',
  strength_balancing: 'Edge weights rebalanced for consistency',
  graph_regeneration: 'Graph fully regenerated by LLM',
}

/**
 * Render a single CEE operation line in the tree format
 */
function CeeOperationLine({
  label,
  op,
  isLast,
}: {
  label: string
  op: CeeOperationInfo
  isLast?: boolean
}) {
  const prefix = isLast ? '└──' : '├──'
  const model = op.model ?? '—'
  const version = op.prompt_version ? `v${op.prompt_version}` : null
  const source = op.prompt_source ? `[${op.prompt_source}]` : null

  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        fontFamily: 'monospace',
        fontSize: 11,
        color: '#475569',
        paddingLeft: 8,
      }}
    >
      <span style={{ color: '#94a3b8' }}>{prefix}</span>
      <span style={{ fontWeight: 500 }}>{label}:</span>
      <span>{model}</span>
      {version && (
        <>
          <span style={{ color: '#94a3b8' }}>·</span>
          <span>{version}</span>
        </>
      )}
      {source && (
        <span
          style={{
            fontSize: 10,
            padding: '1px 4px',
            borderRadius: 3,
            background: '#f1f5f9',
            color: '#64748b',
          }}
        >
          {source}
        </span>
      )}
      {op.degraded && (
        <span
          style={{
            fontSize: 10,
            padding: '1px 4px',
            borderRadius: 3,
            background: '#fef3c7',
            color: '#d97706',
          }}
        >
          degraded
        </span>
      )}
    </div>
  )
}

/**
 * Copy text to clipboard with fallback for older browsers.
 * Returns true on success, false on failure.
 */
async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    }
    // Fallback for older browsers
    const textarea = document.createElement('textarea')
    textarea.value = text
    textarea.style.position = 'fixed'
    textarea.style.left = '-9999px'
    document.body.appendChild(textarea)
    textarea.select()
    const success = document.execCommand('copy')
    document.body.removeChild(textarea)
    return success
  } catch {
    return false
  }
}

function LlmRawSection({
  llmRaw,
  llmRawPathFound,
}: {
  llmRaw: LlmRawData | undefined
  llmRawPathFound: string | null
}) {
  const [showRawText, setShowRawText] = useState(false)
  const [copyFeedback, setCopyFeedback] = useState<'success' | 'error' | null>(null)

  const handleCopyHash = useCallback(async () => {
    if (llmRaw?.hash) {
      const success = await copyToClipboard(llmRaw.hash)
      setCopyFeedback(success ? 'success' : 'error')
      setTimeout(() => setCopyFeedback(null), 1500)
    }
  }, [llmRaw?.hash])

  const handleCopyText = useCallback(async () => {
    if (llmRaw?.text) {
      const success = await copyToClipboard(llmRaw.text)
      setCopyFeedback(success ? 'success' : 'error')
      setTimeout(() => setCopyFeedback(null), 1500)
    }
  }, [llmRaw?.text])

  if (!llmRaw) {
    return (
      <div
        style={{
          marginTop: 12,
          padding: 12,
          background: '#f8fafc',
          borderRadius: 6,
          border: '1px solid #e2e8f0',
        }}
      >
        <div style={{ fontSize: 11, fontWeight: 600, color: '#64748b', marginBottom: 4 }}>
          Raw LLM output
        </div>
        <div style={{ fontSize: 12, color: '#94a3b8' }}>
          Not available — CEE response does not include llm_raw data
        </div>
        {llmRawPathFound === null && (
          <div style={{ fontSize: 10, color: '#94a3b8', marginTop: 4, fontFamily: 'monospace' }}>
            Checked paths: response.trace.pipeline.llm_raw, response.trace.llm_raw, response.pipeline_trace.llm_raw, response.llm_raw
          </div>
        )}
      </div>
    )
  }

  return (
    <details
      style={{
        marginTop: 12,
        padding: 12,
        background: '#f0fdf4',
        borderRadius: 6,
        border: '1px solid #86efac',
      }}
    >
      <summary
        style={{
          fontSize: 11,
          fontWeight: 600,
          color: '#166534',
          cursor: 'pointer',
          userSelect: 'none',
        }}
      >
        Raw LLM output {llmRaw.truncated && <span style={{ color: '#f59e0b' }}>(truncated)</span>}
      </summary>

      <div style={{ marginTop: 12 }}>
        {/* Metadata Grid */}
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(2, 1fr)',
            gap: '8px 16px',
            fontSize: 12,
            marginBottom: 12,
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <span style={{ color: '#64748b' }}>Hash</span>
            <span
              style={{ fontFamily: 'monospace', cursor: llmRaw.hash ? 'pointer' : 'default' }}
              onClick={handleCopyHash}
              title={llmRaw.hash ? 'Click to copy' : ''}
            >
              {llmRaw.hash ?? '—'}{' '}
              {copyFeedback === 'success' && <span style={{ color: '#16a34a' }}>✓</span>}
              {copyFeedback === 'error' && <span style={{ color: '#dc2626' }}>✗</span>}
            </span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <span style={{ color: '#64748b' }}>Characters</span>
            <span style={{ fontFamily: 'monospace' }}>
              {llmRaw.char_count?.toLocaleString() ?? '—'}
            </span>
          </div>
          {llmRaw.node_counts && (
            <>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Options</span>
                <span style={{ fontFamily: 'monospace' }}>{llmRaw.node_counts.options ?? '—'}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Factors</span>
                <span style={{ fontFamily: 'monospace' }}>{llmRaw.node_counts.factors ?? '—'}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Outcomes</span>
                <span style={{ fontFamily: 'monospace' }}>{llmRaw.node_counts.outcomes ?? '—'}</span>
              </div>
            </>
          )}
          {llmRaw.edge_count !== undefined && (
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#64748b' }}>Edges</span>
              <span style={{ fontFamily: 'monospace' }}>{llmRaw.edge_count}</span>
            </div>
          )}
        </div>

        {/* Truncation Warning */}
        {llmRaw.truncated && (
          <div
            style={{
              padding: 8,
              background: '#fffbeb',
              border: '1px solid #fde68a',
              borderRadius: 4,
              fontSize: 11,
              color: '#92400e',
              marginBottom: 12,
            }}
          >
            ⚠ Output was truncated during capture
          </div>
        )}

        {/* Source Path */}
        {llmRawPathFound && (
          <div style={{ fontSize: 10, color: '#64748b', marginBottom: 12, fontFamily: 'monospace' }}>
            Source: {llmRawPathFound}
          </div>
        )}

        {/* Raw Text Toggle */}
        {llmRaw.text && (
          <>
            <button
              onClick={() => setShowRawText((v) => !v)}
              style={{
                padding: '6px 12px',
                fontSize: 11,
                cursor: 'pointer',
                border: '1px solid #e2e8f0',
                borderRadius: 4,
                background: '#fff',
                marginRight: 8,
              }}
            >
              {showRawText ? 'Hide Raw Text' : 'View Raw Text'}
            </button>
            <button
              onClick={handleCopyText}
              style={{
                padding: '6px 12px',
                fontSize: 11,
                cursor: 'pointer',
                border: '1px solid #e2e8f0',
                borderRadius: 4,
                background: '#fff',
              }}
            >
              Copy Raw Text{' '}
              {copyFeedback === 'success' && <span style={{ color: '#16a34a' }}>✓</span>}
              {copyFeedback === 'error' && <span style={{ color: '#dc2626' }}>✗</span>}
            </button>

            {showRawText && (
              <pre
                style={{
                  marginTop: 12,
                  padding: 12,
                  fontSize: 11,
                  fontFamily: 'monospace',
                  background: '#fff',
                  borderRadius: 4,
                  border: '1px solid #e2e8f0',
                  overflow: 'auto',
                  maxHeight: 300,
                  whiteSpace: 'pre-wrap',
                  wordBreak: 'break-word',
                }}
              >
                {llmRaw.text}
              </pre>
            )}
          </>
        )}
      </div>
    </details>
  )
}

export interface PipelineTabProps {
  /** Debug data from useDebugData hook */
  data: DebugData
}

function formatNodeCounts(counts: Record<string, number> | undefined): string {
  if (!counts) return 'No data'
  const parts: string[] = []
  const labels: Record<string, string> = {
    decision: 'decision',
    goal: 'goal',
    option: 'options',
    factor: 'factors',
    outcome: 'outcomes',
  }
  for (const [key, singular] of Object.entries(labels)) {
    const count = counts[key]
    if (typeof count === 'number' && count > 0) {
      parts.push(`${count} ${count === 1 ? singular : singular}`)
    }
  }
  return parts.join(', ') || 'No nodes'
}

/**
 * Calculate total count from node counts object
 */
function getTotalCount(counts?: Record<string, number>): number {
  if (!counts) return 0
  return Object.values(counts).reduce((sum, n) => sum + n, 0)
}

/**
 * Calculate and format delta between stages
 */
function formatDelta(current?: Record<string, number>, previous?: Record<string, number>): string | null {
  if (!current || !previous) return null
  const currentTotal = getTotalCount(current)
  const previousTotal = getTotalCount(previous)
  const delta = currentTotal - previousTotal
  if (delta === 0) return null
  return delta > 0 ? `+${delta}` : String(delta)
}

function ArtefactChip({
  label,
  counts,
  status,
  previousCounts,
}: {
  label: string
  counts?: Record<string, number>
  status: 'ok' | 'warn' | 'error' | 'neutral'
  previousCounts?: Record<string, number>
}) {
  const colors = {
    ok: { bg: '#dcfce7', border: '#86efac', text: '#166534' },
    warn: { bg: '#fef9c3', border: '#fde047', text: '#854d0e' },
    error: { bg: '#fee2e2', border: '#fca5a5', text: '#991b1b' },
    neutral: { bg: '#f8fafc', border: '#e2e8f0', text: '#64748b' },
  }
  const c = colors[status]

  const delta = formatDelta(counts, previousCounts)
  const deltaColor = delta?.startsWith('+') ? '#16a34a' : '#dc2626'

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 4,
        padding: '8px 12px',
        background: c.bg,
        border: `1px solid ${c.border}`,
        borderRadius: 6,
        minWidth: 100,
      }}
    >
      <span style={{ fontSize: 11, fontWeight: 600, color: c.text }}>{label}</span>
      <span style={{ fontSize: 10, fontFamily: 'monospace', color: '#64748b' }}>
        {formatNodeCounts(counts)}
        {delta && (
          <span style={{ color: deltaColor, fontWeight: 600, marginLeft: 4 }}>
            ({delta})
          </span>
        )}
      </span>
    </div>
  )
}

function Arrow() {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        color: '#94a3b8',
        fontSize: 14,
        padding: '0 4px',
      }}
      aria-hidden="true"
    >
      →
    </div>
  )
}

/**
 * Display a single graph correction made by CEE pipeline
 */
function CorrectionItem({ correction }: { correction: GraphCorrection }) {
  const layerColors: Record<string, { bg: string; text: string }> = {
    adapter: { bg: '#dbeafe', text: '#1d4ed8' },
    pipeline: { bg: '#f3e8ff', text: '#7c3aed' },
    guards: { bg: '#fef3c7', text: '#d97706' },
  }

  const typeColors: Record<string, { bg: string; text: string }> = {
    node_added: { bg: '#dcfce7', text: '#166534' },
    node_removed: { bg: '#fee2e2', text: '#991b1b' },
    edge_added: { bg: '#dcfce7', text: '#166534' },
    edge_removed: { bg: '#fee2e2', text: '#991b1b' },
    node_modified: { bg: '#fef9c3', text: '#854d0e' },
    edge_modified: { bg: '#fef9c3', text: '#854d0e' },
    kind_normalised: { bg: '#e0e7ff', text: '#4338ca' },
    coefficient_adjusted: { bg: '#e0e7ff', text: '#4338ca' },
  }

  const layerColor = layerColors[correction.layer] ?? { bg: '#f1f5f9', text: '#64748b' }
  const typeColor = typeColors[correction.type] ?? { bg: '#f1f5f9', text: '#64748b' }

  const targetText = correction.target.node_id ?? correction.target.edge_id ?? '—'

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: 4,
        padding: '8px 10px',
        background: '#f8fafc',
        border: '1px solid #e2e8f0',
        borderRadius: 6,
      }}
    >
      {/* Header row: layer badge, type badge, target */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
        <span
          style={{
            fontSize: 9,
            fontWeight: 600,
            textTransform: 'uppercase',
            padding: '2px 5px',
            borderRadius: 3,
            background: layerColor.bg,
            color: layerColor.text,
          }}
        >
          {correction.layer}
        </span>
        <span
          style={{
            fontSize: 9,
            fontWeight: 600,
            textTransform: 'uppercase',
            padding: '2px 5px',
            borderRadius: 3,
            background: typeColor.bg,
            color: typeColor.text,
          }}
        >
          {correction.type.replace(/_/g, ' ')}
        </span>
        <span
          style={{
            fontSize: 10,
            fontFamily: 'monospace',
            color: '#64748b',
            marginLeft: 'auto',
          }}
        >
          {targetText}
        </span>
      </div>
      {/* Reason row */}
      <div style={{ fontSize: 11, color: '#334155' }}>{correction.reason}</div>
    </div>
  )
}

/**
 * Display a metric card for graph quality metrics
 */
function MetricCard({
  label,
  value,
  warn,
}: {
  label: string
  value: unknown
  warn?: boolean
}) {
  const displayValue = typeof value === 'boolean'
    ? (value ? 'Yes' : 'No')
    : String(value ?? '—')

  return (
    <div
      style={{
        padding: 8,
        background: warn ? '#fef2f2' : '#f9fafb',
        border: `1px solid ${warn ? '#fecaca' : '#e5e7eb'}`,
        borderRadius: 4,
        textAlign: 'center',
      }}
    >
      <div style={{ fontSize: 10, color: '#6b7280', marginBottom: 4 }}>
        {label}
      </div>
      <div
        style={{
          fontSize: 14,
          fontWeight: 600,
          fontFamily: 'monospace',
          color: warn ? '#dc2626' : '#334155',
        }}
      >
        {displayValue}
      </div>
    </div>
  )
}

/**
 * Display a single graph diff item from CEE observability
 */
function GraphDiffItem({ diff }: { diff: GraphDiff }) {
  const operationColors: Record<string, { bg: string; text: string; symbol: string }> = {
    add_node: { bg: '#dcfce7', text: '#166534', symbol: '+' },
    add_edge: { bg: '#dcfce7', text: '#166534', symbol: '+' },
    remove_node: { bg: '#fee2e2', text: '#991b1b', symbol: '-' },
    remove_edge: { bg: '#fee2e2', text: '#991b1b', symbol: '-' },
    update_node: { bg: '#fef9c3', text: '#854d0e', symbol: '~' },
    update_edge: { bg: '#fef9c3', text: '#854d0e', symbol: '~' },
  }

  const opColor = operationColors[diff.operation] ?? { bg: '#f1f5f9', text: '#64748b', symbol: '?' }

  const operationLabel = {
    add_node: '+ Node',
    remove_node: '- Node',
    add_edge: '+ Edge',
    remove_edge: '- Edge',
    update_node: '~ Node',
    update_edge: '~ Edge',
  }[diff.operation] ?? diff.operation

  return (
    <div
      style={{
        padding: 10,
        background: '#fff',
        border: '1px solid #e5e7eb',
        borderRadius: 6,
        fontSize: 11,
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <span
          style={{
            fontWeight: 600,
            color: opColor.text,
            background: opColor.bg,
            padding: '2px 6px',
            borderRadius: 3,
            fontSize: 10,
          }}
        >
          {operationLabel}
        </span>
        <span style={{ fontFamily: 'monospace', color: '#6b7280' }}>
          {diff.target_id}
        </span>
        {diff.repair_type && (
          <span
            style={{
              fontSize: 9,
              padding: '2px 4px',
              background: '#fef3c7',
              borderRadius: 2,
              color: '#92400e',
            }}
          >
            {diff.repair_type}
          </span>
        )}
      </div>

      {diff.reason && (
        <div style={{ color: '#6b7280', marginBottom: 8 }}>
          {diff.reason}
        </div>
      )}

      {(diff.before || diff.after) && (
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: diff.before && diff.after ? '1fr 1fr' : '1fr',
            gap: 8,
            marginTop: 8,
          }}
        >
          {diff.before && (
            <div
              style={{
                padding: 6,
                background: '#fef2f2',
                borderRadius: 4,
                fontFamily: 'monospace',
                fontSize: 10,
              }}
            >
              <div style={{ color: '#dc2626', fontWeight: 600, marginBottom: 4 }}>Before:</div>
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap', color: '#6b7280' }}>
                {JSON.stringify(diff.before, null, 2)}
              </pre>
            </div>
          )}
          {diff.after && (
            <div
              style={{
                padding: 6,
                background: '#f0fdf4',
                borderRadius: 4,
                fontFamily: 'monospace',
                fontSize: 10,
              }}
            >
              <div style={{ color: '#16a34a', fontWeight: 600, marginBottom: 4 }}>After:</div>
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap', color: '#6b7280' }}>
                {JSON.stringify(diff.after, null, 2)}
              </pre>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// =============================================================================
// Pipeline observability components
// =============================================================================

const MAX_TABLE_ROWS = 50

/** Split pipeline_path string with delimiter tolerance: ' → ', '→', '->' */
function splitPipelinePath(pathStr: string): string[] {
  return pathStr.split(/\s*(?:→|->)\s*/).map(s => s.trim()).filter(Boolean)
}

function PipelinePathIndicator({
  pipeline,
  sectionStyle,
  sectionTitleStyle,
}: {
  pipeline: DebugData['pipeline']
  sectionStyle: CSSProperties
  sectionTitleStyle: CSSProperties
}) {
  const stages = useMemo(() => {
    const pathStr = pipeline.cee_provenance?.pipeline_path
    if (typeof pathStr === 'string' && pathStr.length > 0) {
      return splitPipelinePath(pathStr)
    }
    // Fallback: derive from field presence
    const derived: string[] = ['cee']
    if (pipeline.enrich) derived.push('enrich')
    if (pipeline.repair) derived.push('repair')
    if (pipeline.strp) derived.push('strp')
    derived.push('plot_v2')
    return derived
  }, [pipeline])

  return (
    <div style={sectionStyle} data-testid="pipeline-path-indicator">
      <div style={sectionTitleStyle}>Pipeline path</div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 4, flexWrap: 'wrap' }}>
        {stages.map((stage, i) => (
          <span key={`${stage}-${i}`} style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
            {i > 0 && <span style={{ color: '#94a3b8', fontSize: 10 }}>{'\u2192'}</span>}
            <span
              style={{
                padding: '2px 8px',
                borderRadius: 4,
                fontSize: 11,
                fontWeight: 500,
                background: '#f1f5f9',
                border: '1px solid #e2e8f0',
                color: '#334155',
                fontFamily: 'monospace',
              }}
            >
              {stage}
            </span>
          </span>
        ))}
      </div>
    </div>
  )
}

function EnrichmentSection({
  enrich,
  sectionStyle,
  sectionTitleStyle,
}: {
  enrich: DebugData['pipeline']['enrich']
  sectionStyle: CSSProperties
  sectionTitleStyle: CSSProperties
}) {
  if (!enrich) return null
  const calledCount = enrich.called_count
  const isMultiple = typeof calledCount === 'number' && calledCount > 1
  return (
    <div style={sectionStyle} data-testid="enrichment-section">
      <div style={sectionTitleStyle}>Enrichment</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
        <div style={{ padding: 8, background: isMultiple ? '#fffbeb' : '#f9fafb', border: `1px solid ${isMultiple ? '#fde68a' : '#e5e7eb'}`, borderRadius: 4, textAlign: 'center' }}>
          <div style={{ fontSize: 10, color: '#6b7280', marginBottom: 4 }}>Called count</div>
          <div style={{ fontSize: 14, fontWeight: 600, fontFamily: 'monospace', color: isMultiple ? '#d97706' : '#334155' }}>
            {calledCount ?? 'N/A'}
          </div>
          {isMultiple && <div style={{ fontSize: 9, color: '#d97706', marginTop: 2 }}>Called {calledCount} times</div>}
        </div>
        <div style={{ padding: 8, background: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: 4, textAlign: 'center' }}>
          <div style={{ fontSize: 10, color: '#6b7280', marginBottom: 4 }}>Extraction mode</div>
          <div style={{ fontSize: 14, fontWeight: 600, fontFamily: 'monospace', color: '#334155' }}>{enrich.extraction_mode ?? 'N/A'}</div>
        </div>
        <div style={{ padding: 8, background: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: 4, textAlign: 'center' }}>
          <div style={{ fontSize: 10, color: '#6b7280', marginBottom: 4 }}>Factors added</div>
          <div style={{ fontSize: 14, fontWeight: 600, fontFamily: 'monospace', color: '#334155' }}>{enrich.factors_added ?? 'N/A'}</div>
        </div>
      </div>
    </div>
  )
}

function CeeRepairSummary({
  repair,
  sectionStyle,
  sectionTitleStyle,
}: {
  repair: Record<string, unknown> | undefined
  sectionStyle: CSSProperties
  sectionTitleStyle: CSSProperties
}) {
  if (!repair) return null
  const applied = Array.isArray((repair as Record<string, unknown>).applied) ? (repair as Record<string, unknown>).applied as Array<Record<string, unknown>> : []
  const skipped = Array.isArray((repair as Record<string, unknown>).skipped) ? (repair as Record<string, unknown>).skipped as string[] : []

  if (applied.length === 0 && skipped.length === 0) {
    return (
      <div style={sectionStyle} data-testid="cee-repair-summary">
        <div style={sectionTitleStyle}>CEE repair summary</div>
        <div style={{ color: '#16a34a', fontSize: 12 }}>No CEE repairs applied</div>
      </div>
    )
  }

  return (
    <div style={sectionStyle} data-testid="cee-repair-summary">
      <div style={sectionTitleStyle}>CEE repair summary</div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {applied.length > 0 && (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
              <thead>
                <tr>
                  <th style={{ textAlign: 'left', padding: '6px 8px', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', fontWeight: 600, color: '#475569', fontSize: 10 }}>Field</th>
                  <th style={{ textAlign: 'left', padding: '6px 8px', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', fontWeight: 600, color: '#475569', fontSize: 10 }}>From</th>
                  <th style={{ textAlign: 'left', padding: '6px 8px', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', fontWeight: 600, color: '#475569', fontSize: 10 }}>To</th>
                  <th style={{ textAlign: 'left', padding: '6px 8px', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', fontWeight: 600, color: '#475569', fontSize: 10 }}>Reason</th>
                </tr>
              </thead>
              <tbody>
                {applied.slice(0, MAX_TABLE_ROWS).map((r, i) => (
                  <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                    <td style={{ padding: '6px 8px', fontFamily: 'monospace', fontSize: 10 }}>{(r.field as string) ?? '?'}</td>
                    <td style={{ padding: '6px 8px', fontFamily: 'monospace', fontSize: 10 }}>{formatValue(r.from)}</td>
                    <td style={{ padding: '6px 8px', fontFamily: 'monospace', fontSize: 10 }}>{formatValue(r.to)}</td>
                    <td style={{ padding: '6px 8px', fontSize: 10 }}>{(r.reason as string) ?? '?'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {applied.length > MAX_TABLE_ROWS && (
              <div style={{ fontSize: 10, color: '#94a3b8', marginTop: 4 }}>+{applied.length - MAX_TABLE_ROWS} more</div>
            )}
          </div>
        )}
        {skipped.length > 0 && (
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: '#64748b', marginBottom: 4 }}>Skipped</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
              {skipped.map((s, i) => (
                <span key={i} style={{ padding: '2px 6px', borderRadius: 3, fontSize: 10, fontFamily: 'monospace', background: '#f1f5f9', color: '#475569' }}>{s}</span>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function StrpMutations({
  strp,
  sectionStyle,
  sectionTitleStyle,
}: {
  strp: Record<string, unknown> | undefined
  sectionStyle: CSSProperties
  sectionTitleStyle: CSSProperties
}) {
  if (!strp) return null
  const mutations = Array.isArray((strp as Record<string, unknown>).mutations) ? (strp as Record<string, unknown>).mutations as Array<Record<string, unknown>> : []

  if (mutations.length === 0) {
    return (
      <div style={sectionStyle} data-testid="strp-mutations">
        <div style={sectionTitleStyle}>STRP mutations</div>
        <div style={{ color: '#16a34a', fontSize: 12 }}>No STRP mutations</div>
      </div>
    )
  }

  return (
    <div style={sectionStyle} data-testid="strp-mutations">
      <div style={sectionTitleStyle}>STRP mutations</div>
      <div style={{ overflowX: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
          <thead>
            <tr>
              <th style={{ textAlign: 'left', padding: '6px 8px', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', fontWeight: 600, color: '#475569', fontSize: 10 }}>Path</th>
              <th style={{ textAlign: 'left', padding: '6px 8px', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', fontWeight: 600, color: '#475569', fontSize: 10 }}>Action</th>
              <th style={{ textAlign: 'left', padding: '6px 8px', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', fontWeight: 600, color: '#475569', fontSize: 10 }}>Reason</th>
            </tr>
          </thead>
          <tbody>
            {mutations.slice(0, MAX_TABLE_ROWS).map((m, i) => (
              <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                <td style={{ padding: '6px 8px', fontFamily: 'monospace', fontSize: 10 }}>{(m.path as string) ?? '?'}</td>
                <td style={{ padding: '6px 8px', fontSize: 10 }}>{(m.action as string) ?? '?'}</td>
                <td style={{ padding: '6px 8px', fontSize: 10 }}>{(m.reason as string) ?? '?'}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {mutations.length > MAX_TABLE_ROWS && (
          <div style={{ fontSize: 10, color: '#94a3b8', marginTop: 4 }}>+{mutations.length - MAX_TABLE_ROWS} more</div>
        )}
      </div>
    </div>
  )
}

/** Format a value for display (handle null/undefined/objects) */
function formatValue(v: unknown): string {
  if (v === null || v === undefined) return '\u2014'
  if (typeof v === 'string') return v
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  try {
    const str = JSON.stringify(v)
    return str.length > 40 ? str.slice(0, 37) + '...' : str
  } catch {
    return '[object]'
  }
}

export function PipelineTab({ data }: PipelineTabProps) {
  const [showFullLlmOutput, setShowFullLlmOutput] = useState(false)

  const nodeExtraction = data.pipeline.node_extraction
  const llmMetadata = data.pipeline.llm_metadata
  const connectivity = data.pipeline.connectivity

  // Artefact chain status
  const rawStatus = nodeExtraction?.raw ? 'ok' : 'neutral'
  const normalisedStatus = nodeExtraction?.normalised ? 'ok' : 'neutral'
  const validatedStatus = nodeExtraction?.validated ? 'ok' : 'neutral'

  const sectionStyle: CSSProperties = {
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 16,
  }

  const sectionTitleStyle: CSSProperties = {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.05em',
    color: '#64748b',
    marginBottom: 12,
  }

  // Build stages for pipeline
  const stages = useMemo(() => {
    const result = []

    // LLM Draft stage
    if (llmMetadata || data.pipeline.stages.some((s) => s.id === 'llm_draft')) {
      const llmStage = data.pipeline.stages.find((s) => s.id === 'llm_draft')
      result.push({
        id: 'llm_draft',
        name: 'LLM Draft',
        status: 'success' as const,
        duration_ms: llmStage?.duration_ms,
        defaultExpanded: true,
        content: (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {/* Metadata grid */}
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(2, 1fr)',
                gap: '8px 16px',
                fontSize: 12,
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Model</span>
                <span style={{ fontFamily: 'monospace' }}>{llmMetadata?.model ?? '—'}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Temperature</span>
                <span style={{ fontFamily: 'monospace' }}>
                  {llmMetadata?.temperature != null ? llmMetadata.temperature : 'N/A'}
                </span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Prompt Tokens</span>
                <span style={{ fontFamily: 'monospace' }}>
                  {llmMetadata?.token_usage?.prompt_tokens ?? '—'}
                </span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Completion Tokens</span>
                <span style={{ fontFamily: 'monospace' }}>
                  {llmMetadata?.token_usage?.completion_tokens ?? '—'}
                </span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Total Tokens</span>
                <span style={{ fontFamily: 'monospace' }}>
                  {llmMetadata?.token_usage?.total_tokens ?? '—'}
                </span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: '#64748b' }}>Duration</span>
                <span style={{ fontFamily: 'monospace' }}>
                  {formatDuration(llmMetadata?.duration_ms ?? llmStage?.duration_ms)}
                </span>
              </div>
            </div>

            {/* View Full button */}
            {llmStage?.details && (
              <button
                onClick={() => setShowFullLlmOutput((v) => !v)}
                style={{
                  padding: '6px 12px',
                  fontSize: 11,
                  cursor: 'pointer',
                  border: '1px solid #e2e8f0',
                  borderRadius: 4,
                  background: '#fff',
                  alignSelf: 'flex-start',
                }}
              >
                {showFullLlmOutput ? 'Hide Full Output' : 'View Full Output'}
              </button>
            )}

            {showFullLlmOutput && llmStage?.details && (
              <JsonViewer data={llmStage.details} maxHeight={300} showCopy />
            )}

            {/* CEE Observability LLM Calls (if available) */}
            {data.cee_observability && data.cee_observability.llm_calls.length > 0 && (
              <details
                style={{
                  padding: 12,
                  background: '#f0fdf4',
                  border: '1px solid #86efac',
                  borderRadius: 6,
                }}
              >
                <summary
                  style={{
                    fontSize: 12,
                    fontWeight: 600,
                    color: '#166534',
                    cursor: 'pointer',
                    userSelect: 'none',
                  }}
                >
                  LLM calls ({data.cee_observability.llm_calls.length})
                  {data.cee_observability.totals && (
                    <span style={{ marginLeft: 8, color: '#6b7280', fontWeight: 400 }}>
                      • {data.cee_observability.totals.total_tokens.total.toLocaleString()} tokens
                      • {(data.cee_observability.totals.total_latency_ms / 1000).toFixed(1)}s
                    </span>
                  )}
                </summary>

                <div style={{ marginTop: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {data.cee_observability.llm_calls.map((call, i) => (
                    <div
                      key={i}
                      style={{
                        padding: 8,
                        background: call.success ? '#f9fafb' : '#fef2f2',
                        border: `1px solid ${call.success ? '#e5e7eb' : '#fecaca'}`,
                        borderRadius: 4,
                        fontSize: 11,
                      }}
                    >
                      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                        <span style={{ fontFamily: 'monospace', fontSize: 10, color: '#6b7280' }}>
                          {call.step}
                          {call.attempt > 1 && (
                            <span style={{ color: '#f59e0b', marginLeft: 4 }}>
                              (attempt {call.attempt})
                            </span>
                          )}
                        </span>
                        <span style={{ fontFamily: 'monospace', fontSize: 10, color: call.success ? '#16a34a' : '#dc2626' }}>
                          {call.success ? '✓' : '✗'}
                        </span>
                      </div>

                      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '4px 12px', fontSize: 10 }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                          <span style={{ color: '#6b7280' }}>Model</span>
                          <span style={{ fontFamily: 'monospace' }}>{call.model}</span>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                          <span style={{ color: '#6b7280' }}>Tokens</span>
                          <span style={{ fontFamily: 'monospace' }}>{call.tokens.total.toLocaleString()}</span>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                          <span style={{ color: '#6b7280' }}>Provider</span>
                          <span style={{ fontFamily: 'monospace' }}>{call.provider}</span>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                          <span style={{ color: '#6b7280' }}>Latency</span>
                          <span style={{ fontFamily: 'monospace' }}>{call.latency_ms}ms</span>
                        </div>
                      </div>

                      {call.error && (
                        <div style={{ marginTop: 4, color: '#dc2626', fontSize: 10 }}>
                          Error: {call.error}
                        </div>
                      )}

                      {call.cache_hit && (
                        <div style={{ marginTop: 4, color: '#16a34a', fontSize: 10 }}>
                          ⚡ Cache hit
                        </div>
                      )}
                    </div>
                  ))}
                </div>

                {/* Token usage summary */}
                {data.cee_observability.totals && (
                  <div style={{ marginTop: 12, padding: 8, background: '#f9fafb', borderRadius: 4, fontSize: 10 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 2 }}>
                      <span style={{ color: '#6b7280' }}>Total Input Tokens:</span>
                      <span style={{ fontFamily: 'monospace' }}>
                        {data.cee_observability.totals.total_tokens.input.toLocaleString()}
                      </span>
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                      <span style={{ color: '#6b7280' }}>Total Output Tokens:</span>
                      <span style={{ fontFamily: 'monospace' }}>
                        {data.cee_observability.totals.total_tokens.output.toLocaleString()}
                      </span>
                    </div>
                  </div>
                )}
              </details>
            )}

            {/* Raw LLM output Section */}
            <LlmRawSection
              llmRaw={data.pipeline.llm_raw}
              llmRawPathFound={data.diagnostics.llm_raw_path_found}
            />
          </div>
        ),
      })
    }

    // Node Extraction stage
    if (nodeExtraction) {
      const extractionStage = data.pipeline.stages.find((s) => s.id === 'node_extraction')
      result.push({
        id: 'node_extraction',
        name: 'Node Extraction',
        status: 'success' as const,
        duration_ms: extractionStage?.duration_ms,
        defaultExpanded: false,
        content: <JsonViewer data={nodeExtraction} maxHeight={300} showCopy />,
      })
    }

    // Transforms stage
    const transformsStage = data.pipeline.stages.find((s) => s.id === 'transforms')
    if (transformsStage) {
      result.push({
        id: 'transforms',
        name: 'Transforms',
        status: 'success' as const,
        duration_ms: transformsStage.duration_ms,
        defaultExpanded: false,
        content: <JsonViewer data={transformsStage.details} maxHeight={300} showCopy />,
      })
    }

    // Final Graph stage
    const finalGraphStage = data.pipeline.stages.find((s) => s.id === 'final_graph')
    if (finalGraphStage) {
      result.push({
        id: 'final_graph',
        name: 'Final Graph',
        status: 'success' as const,
        duration_ms: finalGraphStage.duration_ms,
        defaultExpanded: false,
        content: <JsonViewer data={finalGraphStage.details} maxHeight={300} showCopy />,
      })
    }

    return result
  }, [data.pipeline.stages, data.pipeline.llm_raw, data.diagnostics.llm_raw_path_found, llmMetadata, nodeExtraction, showFullLlmOutput])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, padding: 12 }}>
      {/* Artefact Chain Summary */}
      <div style={sectionStyle}>
        <div style={sectionTitleStyle}>Artefact chain</div>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 4,
            flexWrap: 'wrap',
          }}
        >
          <ArtefactChip label="Raw" counts={nodeExtraction?.raw} status={rawStatus} />
          <Arrow />
          <ArtefactChip
            label="Normalised"
            counts={nodeExtraction?.normalised}
            status={normalisedStatus}
            previousCounts={nodeExtraction?.raw}
          />
          <Arrow />
          <ArtefactChip
            label="Validated"
            counts={nodeExtraction?.validated}
            status={validatedStatus}
            previousCounts={nodeExtraction?.normalised}
          />
        </div>
      </div>

      {/* Pipeline path indicator */}
      <PipelinePathIndicator pipeline={data.pipeline} sectionStyle={sectionStyle} sectionTitleStyle={sectionTitleStyle} />

      {/* Enrichment call count */}
      <EnrichmentSection enrich={data.pipeline.enrich} sectionStyle={sectionStyle} sectionTitleStyle={sectionTitleStyle} />

      {/* CEE repair summary */}
      <CeeRepairSummary repair={data.pipeline.repair} sectionStyle={sectionStyle} sectionTitleStyle={sectionTitleStyle} />

      {/* STRP mutations */}
      <StrpMutations strp={data.pipeline.strp} sectionStyle={sectionStyle} sectionTitleStyle={sectionTitleStyle} />

      {/* CEE Operations Model/Prompt Info */}
      {data.cee_operations && (
        <div style={sectionStyle}>
          <div style={sectionTitleStyle}>CEE operations</div>
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: 4,
              padding: '8px 0',
            }}
          >
            {data.cee_operations.draft_graph && (
              <CeeOperationLine
                label="Draft Graph"
                op={data.cee_operations.draft_graph}
                isLast={!data.cee_operations.decision_review && !data.cee_operations.explain_graph}
              />
            )}
            {data.cee_operations.decision_review && (
              <CeeOperationLine
                label="Decision Review"
                op={data.cee_operations.decision_review}
                isLast={!data.cee_operations.explain_graph}
              />
            )}
            {data.cee_operations.explain_graph && (
              <CeeOperationLine
                label="Explain"
                op={data.cee_operations.explain_graph}
                isLast={true}
              />
            )}
          </div>
        </div>
      )}

      {/* CEE Processing Table (Phase B1) */}
      {data.cee_observability && data.cee_observability.llm_calls.length > 0 && (
        <div style={sectionStyle}>
          <div style={sectionTitleStyle}>CEE processing</div>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
              <thead>
                <tr style={{ borderBottom: '2px solid #e2e8f0' }}>
                  <th style={{ textAlign: 'left', padding: '8px 12px', color: '#64748b', fontWeight: 600 }}>Step</th>
                  <th style={{ textAlign: 'left', padding: '8px 12px', color: '#64748b', fontWeight: 600 }}>Prompt</th>
                  <th style={{ textAlign: 'left', padding: '8px 12px', color: '#64748b', fontWeight: 600 }}>Model</th>
                  <th style={{ textAlign: 'right', padding: '8px 12px', color: '#64748b', fontWeight: 600 }}>Tokens</th>
                  <th style={{ textAlign: 'right', padding: '8px 12px', color: '#64748b', fontWeight: 600 }}>Duration</th>
                  <th style={{ textAlign: 'center', padding: '8px 12px', color: '#64748b', fontWeight: 600 }}>Status</th>
                </tr>
              </thead>
              <tbody>
                {(() => {
                  // Build timeline using timestamps for accurate chronological ordering
                  type RowData = {
                    type: 'llm' | 'validate'
                    step: string
                    prompt?: string
                    model?: string
                    tokens?: { input: number; output: number }
                    duration_ms: number
                    success: boolean
                    error?: string
                    isRepair?: boolean
                    validationFailed?: { count: number; rules: string[] }
                    timestamp: number // For sorting
                  }

                  const rows: RowData[] = []
                  const llmCalls = data.cee_observability!.llm_calls
                  const validationAttempts = data.cee_observability?.validation?.attempt_records ?? []

                  // Add LLM calls with timestamps
                  llmCalls.forEach((call) => {
                    const timestamp = call.started_at ? new Date(call.started_at).getTime() : 0
                    rows.push({
                      type: 'llm',
                      step: call.step,
                      prompt: call.prompt_version,
                      model: call.model,
                      tokens: { input: call.tokens.input, output: call.tokens.output },
                      duration_ms: call.latency_ms,
                      success: call.success,
                      error: call.error,
                      isRepair: call.step === 'repair_graph',
                      timestamp,
                    })
                  })

                  // Add validation attempts with timestamps
                  validationAttempts.forEach((attempt, i) => {
                    const timestamp = attempt.timestamp ? new Date(attempt.timestamp).getTime() : 0
                    rows.push({
                      type: 'validate',
                      step: `validate #${i + 1}`,
                      duration_ms: attempt.latency_ms,
                      success: attempt.passed,
                      validationFailed: !attempt.passed ? {
                        count: attempt.rules_failed.length,
                        rules: attempt.rules_failed,
                      } : undefined,
                      timestamp,
                    })
                  })

                  // Sort by timestamp for chronological order
                  rows.sort((a, b) => {
                    if (a.timestamp > 0 && b.timestamp > 0) {
                      return a.timestamp - b.timestamp
                    }
                    return 0 // Keep original order if timestamps missing
                  })

                  return rows.map((row, i) => (
                    <tr
                      key={i}
                      style={{
                        borderBottom: '1px solid #e2e8f0',
                        background: row.isRepair ? '#fffbeb' : (!row.success ? '#fef2f2' : 'transparent'),
                      }}
                    >
                      <td style={{ padding: '8px 12px', fontFamily: 'monospace', fontWeight: 500 }}>
                        {row.isRepair && <span style={{ marginRight: 4 }}>⚡</span>}
                        {row.step}
                      </td>
                      <td style={{ padding: '8px 12px', fontFamily: 'monospace', color: '#6b7280' }}>
                        {row.prompt ?? '—'}
                      </td>
                      <td style={{ padding: '8px 12px', fontFamily: 'monospace', color: '#6b7280' }}>
                        {row.model ?? '—'}
                      </td>
                      <td style={{ padding: '8px 12px', textAlign: 'right', fontFamily: 'monospace' }}>
                        {row.tokens ? `${row.tokens.input.toLocaleString()}→${row.tokens.output.toLocaleString()}` : '—'}
                      </td>
                      <td style={{ padding: '8px 12px', textAlign: 'right', fontFamily: 'monospace' }}>
                        {formatDuration(row.duration_ms)}
                      </td>
                      <td style={{ padding: '8px 12px', textAlign: 'center' }}>
                        {row.success ? (
                          <span style={{ color: '#16a34a' }}>✓</span>
                        ) : (
                          <span style={{ color: '#dc2626' }} title={row.error || row.validationFailed?.rules.join(', ')}>
                            ✗ {row.validationFailed && `${row.validationFailed.count} failed`}
                          </span>
                        )}
                      </td>
                    </tr>
                  ))
                })()}
              </tbody>
            </table>
          </div>

          {/* Summary footer */}
          {data.cee_observability.totals && (
            <div style={{ marginTop: 12, padding: 8, background: '#f8fafc', borderRadius: 4, fontSize: 11, display: 'flex', gap: 16, flexWrap: 'wrap' }}>
              <span>
                <strong>Total Tokens:</strong>{' '}
                {data.cee_observability.totals.total_tokens.input.toLocaleString()}→{data.cee_observability.totals.total_tokens.output.toLocaleString()}
              </span>
              <span>
                <strong>Total Duration:</strong> {formatDuration(data.cee_observability.totals.total_latency_ms)}
              </span>
              <span>
                <strong>LLM Calls:</strong> {data.cee_observability.totals.total_llm_calls}
              </span>
              {data.cee_observability.validation?.repairs_triggered && (
                <span style={{ color: '#d97706' }}>
                  <strong>Repairs:</strong> {data.cee_observability.validation.repair_types.length}
                </span>
              )}
            </div>
          )}

          {/* Model Selection Details (Phase B2) */}
          <details style={{ marginTop: 12 }}>
            <summary style={{ fontSize: 11, fontWeight: 600, color: '#64748b', cursor: 'pointer', userSelect: 'none' }}>
              Model Selection Details
            </summary>
            <div style={{ marginTop: 8, display: 'flex', flexDirection: 'column', gap: 8 }}>
              {data.cee_observability.llm_calls.map((call, i) => (
                <div
                  key={i}
                  style={{
                    padding: 8,
                    background: '#f9fafb',
                    border: '1px solid #e5e7eb',
                    borderRadius: 4,
                    fontSize: 11,
                  }}
                >
                  <div style={{ fontWeight: 600, marginBottom: 4, fontFamily: 'monospace' }}>
                    {call.step}
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 2, paddingLeft: 12 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                      <span style={{ color: '#94a3b8' }}>├─</span>
                      <span style={{ color: '#6b7280' }}>Model:</span>
                      <span style={{ fontFamily: 'monospace' }}>{call.model}</span>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                      <span style={{ color: '#94a3b8' }}>├─</span>
                      <span style={{ color: '#6b7280' }}>Provider:</span>
                      <span style={{ fontFamily: 'monospace' }}>{call.provider}</span>
                    </div>
                    {call.prompt_version && (
                      <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                        <span style={{ color: '#94a3b8' }}>├─</span>
                        <span style={{ color: '#6b7280' }}>Prompt:</span>
                        <span style={{ fontFamily: 'monospace' }}>{call.prompt_version}</span>
                      </div>
                    )}
                    {call.prompt_hash && (
                      <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                        <span style={{ color: '#94a3b8' }}>├─</span>
                        <span style={{ color: '#6b7280' }}>Hash:</span>
                        <span style={{ fontFamily: 'monospace', fontSize: 10 }}>{call.prompt_hash.slice(0, 12)}...</span>
                      </div>
                    )}
                    {call.cache_hit !== undefined && (
                      <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                        <span style={{ color: '#94a3b8' }}>└─</span>
                        <span style={{ color: '#6b7280' }}>Cache:</span>
                        <span style={{ fontFamily: 'monospace', color: call.cache_hit ? '#16a34a' : '#6b7280' }}>
                          {call.cache_hit ? 'hit' : 'miss'}
                        </span>
                      </div>
                    )}
                    {!call.prompt_version && !call.prompt_hash && call.cache_hit === undefined && (
                      <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                        <span style={{ color: '#94a3b8' }}>└─</span>
                        <span style={{ color: '#9ca3af', fontStyle: 'italic' }}>No additional config available</span>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </details>
        </div>
      )}

      {/* CEE Trace Diagnostic */}
      {data.ceeTrace && (
        <div
          style={{
            ...sectionStyle,
            background: data.ceeTrace.degraded ? '#fffbeb' : '#f0fdf4',
            border: `1px solid ${data.ceeTrace.degraded ? '#fde68a' : '#86efac'}`,
          }}
        >
          <div
            style={{
              fontSize: 13,
              fontWeight: 600,
              color: data.ceeTrace.degraded ? '#92400e' : '#166534',
              marginBottom: 8,
            }}
          >
            {data.ceeTrace.degraded ? '⚠ CEE Degraded Mode' : '✓ CEE Normal'}
          </div>
          {data.ceeTrace.reason && (
            <div style={{ fontSize: 12, color: '#64748b', marginBottom: 4 }}>
              Reason: <code style={{ fontFamily: 'monospace', background: '#f1f5f9', padding: '1px 4px', borderRadius: 2 }}>{data.ceeTrace.reason}</code>
            </div>
          )}
          {data.ceeTrace.latency_ms !== undefined && (
            <div style={{ fontSize: 12, color: '#64748b', marginBottom: 4 }}>
              Latency: {formatDuration(data.ceeTrace.latency_ms)}
            </div>
          )}
          {data.ceeTrace.source && (
            <div style={{ fontSize: 12, color: '#64748b' }}>
              Source: {data.ceeTrace.source}
            </div>
          )}
        </div>
      )}

      {/* Connectivity Summary */}
      {connectivity && (
        <div style={sectionStyle}>
          <div style={sectionTitleStyle}>Graph connectivity</div>
          <div style={{ fontSize: 12, color: '#334155' }}>
            {connectivity.decision_count > 0 && `${connectivity.decision_count} decision`}
            {connectivity.option_count > 0 && ` → ${connectivity.option_count} options`}
            {connectivity.factor_count > 0 && ` ← ${connectivity.factor_count} factors`}
            {connectivity.goal_count > 0 && ` → ${connectivity.goal_count} goal`}
            {connectivity.edge_count > 0 && ` (${connectivity.edge_count} edges)`}
          </div>
        </div>
      )}

      {/* Graph Corrections */}
      {data.corrections.length > 0 && (
        <div style={sectionStyle}>
          <div style={sectionTitleStyle}>
            Graph corrections
            {data.correctionsSummary && (
              <span style={{ fontWeight: 400, marginLeft: 8 }}>
                ({data.correctionsSummary.total} total)
              </span>
            )}
          </div>
          {data.correctionsSummary && (
            <div style={{ fontSize: 11, color: '#64748b', marginBottom: 8 }}>
              {Object.entries(data.correctionsSummary.by_layer)
                .filter(([, count]) => count && count > 0)
                .map(([layer, count]) => `${layer}: ${count}`)
                .join(' | ')}
            </div>
          )}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {data.corrections.map((correction) => (
              <CorrectionItem key={correction.id} correction={correction} />
            ))}
          </div>

          {/* Graph Repair Diff View (Phase B4) - Git-diff style view */}
          <details style={{ marginTop: 12 }}>
            <summary style={{ fontSize: 11, fontWeight: 600, color: '#64748b', cursor: 'pointer', userSelect: 'none' }}>
              Graph Repair Diff
            </summary>
            <div style={{ marginTop: 8, fontFamily: 'monospace', fontSize: 11, background: '#1e293b', color: '#e2e8f0', padding: 12, borderRadius: 6, overflow: 'auto' }}>
              {/* Group corrections by node vs edge changes */}
              {(() => {
                const nodeChanges = data.corrections.filter(c =>
                  c.type === 'node_added' || c.type === 'node_removed' || c.type === 'node_modified' || c.type === 'kind_normalised'
                )
                const edgeChanges = data.corrections.filter(c =>
                  c.type === 'edge_added' || c.type === 'edge_removed' || c.type === 'edge_modified' || c.type === 'coefficient_adjusted'
                )

                const getPrefix = (type: string) => {
                  if (type.includes('added')) return { symbol: '+', color: '#4ade80' }
                  if (type.includes('removed')) return { symbol: '-', color: '#f87171' }
                  return { symbol: '~', color: '#fbbf24' }
                }

                // Build descriptive target string, using reason as fallback when IDs missing
                const getNodeTarget = (c: typeof data.corrections[0]) => {
                  if (c.target.node_id) return c.target.node_id
                  // Extract node reference from reason if possible
                  const reasonMatch = c.reason?.match(/node\s+["']?([^"'\s]+)["']?/i)
                  if (reasonMatch) return reasonMatch[1]
                  // Fallback to stage_name or type description
                  return c.stage_name || `[${c.type.replace(/_/g, ' ')}]`
                }

                const getEdgeTarget = (c: typeof data.corrections[0]) => {
                  if (c.target.edge_id) return c.target.edge_id
                  if (c.target.node_id) return `${c.target.node_id} → ...`
                  // Extract edge reference from reason if possible
                  const reasonMatch = c.reason?.match(/edge\s+["']?([^"'\s→]+)["']?\s*→\s*["']?([^"'\s]+)["']?/i)
                  if (reasonMatch) return `${reasonMatch[1]} → ${reasonMatch[2]}`
                  // Fallback to abbreviated reason
                  if (c.reason && c.reason.length < 40) return `[${c.reason}]`
                  return c.stage_name || `[${c.type.replace(/_/g, ' ')}]`
                }

                return (
                  <>
                    {nodeChanges.length > 0 && (
                      <div style={{ marginBottom: 8 }}>
                        <div style={{ color: '#94a3b8', marginBottom: 4 }}>Nodes:</div>
                        {nodeChanges.map((c, i) => {
                          const { symbol, color } = getPrefix(c.type)
                          const target = getNodeTarget(c)
                          return (
                            <div key={i} style={{ color, paddingLeft: 8 }}>
                              {symbol} {target} ({c.type.replace(/_/g, ' ')})
                            </div>
                          )
                        })}
                      </div>
                    )}
                    {edgeChanges.length > 0 && (
                      <div>
                        <div style={{ color: '#94a3b8', marginBottom: 4 }}>Edges:</div>
                        {edgeChanges.map((c, i) => {
                          const { symbol, color } = getPrefix(c.type)
                          const target = getEdgeTarget(c)
                          const detail = c.type === 'coefficient_adjusted' && c.reason
                            ? ` (${c.reason})`
                            : ` (${c.type.replace(/_/g, ' ')})`
                          return (
                            <div key={i} style={{ color, paddingLeft: 8 }}>
                              {symbol} {target}{detail}
                            </div>
                          )
                        })}
                      </div>
                    )}
                    {nodeChanges.length === 0 && edgeChanges.length === 0 && (
                      <div style={{ color: '#94a3b8' }}>No structural changes</div>
                    )}
                  </>
                )
              })()}
            </div>
          </details>
        </div>
      )}

      {/* Pipeline Stages */}
      <div style={sectionStyle}>
        <div style={sectionTitleStyle}>Pipeline stages</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {stages.length > 0 ? (
            stages.map((stage) => (
              <PipelineStage
                key={stage.id}
                name={stage.name}
                status={stage.status}
                duration_ms={stage.duration_ms}
                defaultExpanded={stage.defaultExpanded}
              >
                {stage.content}
              </PipelineStage>
            ))
          ) : (
            <div
              style={{
                padding: 16,
                textAlign: 'center',
                color: '#94a3b8',
                fontSize: 12,
              }}
            >
              No pipeline stages recorded
            </div>
          )}
        </div>
      </div>

      {/* Validation Attempts (CEE Observability) */}
      {data.cee_observability?.validation &&
       data.cee_observability.validation.attempt_records.length > 0 && (
        <div style={sectionStyle}>
          <div style={sectionTitleStyle}>
            Validation attempts ({data.cee_observability.validation.attempts})
            {data.cee_observability.validation.repairs_triggered && (
              <span style={{ marginLeft: 8, color: '#f59e0b', fontWeight: 400, fontSize: 11 }}>
                Repairs applied
              </span>
            )}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {data.cee_observability.validation.attempt_records.map((attempt, i) => (
              <div
                key={i}
                style={{
                  padding: 12,
                  background: attempt.passed ? '#f0fdf4' : '#fef2f2',
                  border: `1px solid ${attempt.passed ? '#86efac' : '#fecaca'}`,
                  borderRadius: 6,
                  fontSize: 12,
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                  <span style={{
                    fontWeight: 600,
                    color: attempt.passed ? '#166534' : '#dc2626',
                  }}>
                    Attempt {attempt.attempt} {attempt.passed ? '✓' : '✗'}
                  </span>
                  <span style={{ fontFamily: 'monospace', color: '#6b7280', fontSize: 11 }}>
                    {attempt.latency_ms}ms
                  </span>
                </div>

                <div style={{ fontSize: 11, color: '#6b7280', marginBottom: 4 }}>
                  {attempt.rules_checked} rules checked
                  {attempt.rules_failed.length > 0 && (
                    <span style={{ color: '#dc2626' }}>
                      {' • '}
                      {attempt.rules_failed.length} failed
                    </span>
                  )}
                </div>

                {/* Failed rules list */}
                {attempt.rules_failed.length > 0 && (
                  <div style={{ marginTop: 8, marginBottom: 8 }}>
                    <div style={{ fontSize: 10, fontWeight: 600, color: '#dc2626', marginBottom: 4 }}>
                      Failed Rules:
                    </div>
                    <ul style={{ margin: 0, paddingLeft: 20, fontSize: 10, color: '#6b7280' }}>
                      {attempt.rules_failed.map((rule, idx) => (
                        <li key={idx}>{rule}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Repairs with explanations */}
                {attempt.repairs_triggered && attempt.repair_types && attempt.repair_types.length > 0 && (
                  <div style={{ marginTop: 8, padding: 8, background: '#fffbeb', border: '1px solid #fde68a', borderRadius: 4 }}>
                    <div style={{ fontSize: 10, fontWeight: 600, color: '#92400e', marginBottom: 4 }}>
                      Repairs applied:
                    </div>
                    <ul style={{ margin: 0, paddingLeft: 20, fontSize: 10, color: '#78716c' }}>
                      {attempt.repair_types.map((type, idx) => (
                        <li key={idx}>
                          <strong>{type}:</strong>{' '}
                          {REPAIR_TYPE_EXPLANATIONS[type] ?? 'Automated fix applied'}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Retry indicator */}
                {attempt.retry_triggered && (
                  <div style={{
                    marginTop: 8,
                    padding: 6,
                    background: '#fef2f2',
                    border: '1px solid #fecaca',
                    borderRadius: 4,
                    fontSize: 10,
                    color: '#dc2626',
                  }}>
                    🔄 Retry triggered after this attempt
                  </div>
                )}

                {/* Warnings */}
                {attempt.warnings && attempt.warnings.length > 0 && (
                  <div style={{ marginTop: 8 }}>
                    <div style={{ fontSize: 10, fontWeight: 600, color: '#d97706', marginBottom: 4 }}>
                      Warnings:
                    </div>
                    <ul style={{ margin: 0, paddingLeft: 20, fontSize: 10, color: '#78716c' }}>
                      {attempt.warnings.map((warning, idx) => (
                        <li key={idx}>{warning}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Graph Quality Metrics (from CEE Observability) */}
      {data.cee_observability?.graph_metrics && (
        <div style={sectionStyle}>
          <div style={sectionTitleStyle}>
            Graph quality metrics
            {data.cee_observability.graph_metrics.has_cycles && (
              <span style={{ marginLeft: 8, color: '#dc2626', fontWeight: 400, fontSize: 11 }}>
                Cycles detected
              </span>
            )}
            {(data.cee_observability.graph_metrics.orphan_nodes as number) > 0 && (
              <span style={{ marginLeft: 8, color: '#f59e0b', fontWeight: 400, fontSize: 11 }}>
                {data.cee_observability.graph_metrics.orphan_nodes} orphans
              </span>
            )}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
            <MetricCard label="Nodes" value={data.cee_observability.graph_metrics.node_count} />
            <MetricCard label="Edges" value={data.cee_observability.graph_metrics.edge_count} />
            <MetricCard label="Depth" value={data.cee_observability.graph_metrics.depth} />
            <MetricCard label="Max Breadth" value={data.cee_observability.graph_metrics.max_breadth} />
            <MetricCard
              label="Cycles"
              value={data.cee_observability.graph_metrics.has_cycles ? 'Yes' : 'No'}
              warn={data.cee_observability.graph_metrics.has_cycles}
            />
            <MetricCard
              label="Orphan Nodes"
              value={data.cee_observability.graph_metrics.orphan_nodes}
              warn={(data.cee_observability.graph_metrics.orphan_nodes as number) > 0}
            />
          </div>

          {/* Additional metrics if present */}
          {Object.keys(data.cee_observability.graph_metrics).filter(
            k => !['node_count', 'edge_count', 'depth', 'max_breadth', 'has_cycles', 'orphan_nodes'].includes(k)
          ).length > 0 && (
            <details style={{ marginTop: 12 }}>
              <summary style={{ fontSize: 11, fontWeight: 600, color: '#64748b', cursor: 'pointer', userSelect: 'none' }}>
                Additional Metrics
              </summary>
              <div style={{ marginTop: 8, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
                {Object.entries(data.cee_observability.graph_metrics)
                  .filter(([k]) => !['node_count', 'edge_count', 'depth', 'max_breadth', 'has_cycles', 'orphan_nodes'].includes(k))
                  .map(([key, value]) => (
                    <MetricCard
                      key={key}
                      label={key.replace(/_/g, ' ')}
                      value={value}
                    />
                  ))}
              </div>
            </details>
          )}
        </div>
      )}

      {/* Graph Repair Diffs (from CEE Observability) */}
      {data.cee_observability?.graph_diffs && data.cee_observability.graph_diffs.length > 0 && (
        <div
          style={{
            ...sectionStyle,
            background: '#fffbeb',
            border: '1px solid #fde68a',
          }}
        >
          <div style={{ ...sectionTitleStyle, color: '#92400e' }}>
            Graph repairs ({data.cee_observability.graph_diffs.length})
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {data.cee_observability.graph_diffs.map((diff, i) => (
              <GraphDiffItem key={i} diff={diff} />
            ))}
          </div>
        </div>
      )}

      {/* M1 Coaching (Deterministic Layer) */}
      {data.m1_coaching && (
        <div
          style={{
            ...sectionStyle,
            background: '#f0fdf4',
            border: '1px solid #bbf7d0',
          }}
        >
          <div style={{ ...sectionTitleStyle, color: '#166534', display: 'flex', alignItems: 'center', gap: 8 }}>
            M1 coaching (deterministic)
            {data.m1_coaching.readiness && (
              <span
                style={{
                  fontSize: 10,
                  padding: '2px 6px',
                  borderRadius: 4,
                  background: data.m1_coaching.readiness === 'ready' ? '#dcfce7' :
                              data.m1_coaching.readiness === 'close_call' ? '#fef3c7' :
                              data.m1_coaching.readiness === 'needs_evidence' ? '#fef2f2' : '#f3f4f6',
                  color: data.m1_coaching.readiness === 'ready' ? '#166534' :
                         data.m1_coaching.readiness === 'close_call' ? '#92400e' :
                         data.m1_coaching.readiness === 'needs_evidence' ? '#991b1b' : '#374151',
                }}
              >
                {data.m1_coaching.readiness.replace('_', ' ')}
              </span>
            )}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
            <MetricCard label="Readiness" value={data.m1_coaching.readiness ?? '—'} />
            <MetricCard label="Score" value={data.m1_coaching.readiness_score ?? '—'} />
            <MetricCard
              label="Evidence Gaps"
              value={data.m1_coaching.evidence_gaps_count}
              warn={data.m1_coaching.evidence_gaps_count > 0}
            />
            <MetricCard label="Key Drivers" value={data.m1_coaching.key_drivers?.count ?? 0} />
            <MetricCard label="Next Actions" value={data.m1_coaching.next_actions_count} />
            <MetricCard
              label="Assumptions"
              value={data.m1_coaching.assumptions_count}
              warn={data.m1_coaching.assumptions_by_severity.high > 0}
            />
          </div>

          {data.m1_coaching.key_drivers?.dominant_factor && (
            <div
              style={{
                marginTop: 12,
                padding: 8,
                background: '#ecfdf5',
                border: '1px solid #a7f3d0',
                borderRadius: 4,
                fontSize: 12,
              }}
            >
              <strong>Dominant Factor:</strong> {data.m1_coaching.key_drivers.dominant_factor}
            </div>
          )}

          {data.m1_coaching.assumptions_by_severity.high > 0 && (
            <div
              style={{
                marginTop: 8,
                padding: 8,
                background: '#fef2f2',
                border: '1px solid #fecaca',
                borderRadius: 4,
                fontSize: 12,
                color: '#991b1b',
              }}
            >
              ⚠️ {data.m1_coaching.assumptions_by_severity.high} high-severity assumption{data.m1_coaching.assumptions_by_severity.high > 1 ? 's' : ''}
            </div>
          )}

          <details style={{ marginTop: 12 }}>
            <summary style={{ cursor: 'pointer', fontSize: 11, color: '#64748b' }}>
              View Raw M1 Coaching Data
            </summary>
            <div style={{ marginTop: 8 }}>
              <JsonViewer data={data.m1_coaching.raw} maxHeight={300} />
            </div>
          </details>
        </div>
      )}

      {/* M2 Decision Review (LLM-Enhanced) */}
      <div
        style={{
          ...sectionStyle,
          background: data.m2_review?.status === 'failed' ? '#fef2f2' :
                      data.m2_review?.status === 'skipped' ? '#f8fafc' :
                      data.m2_review?.status === 'success' ? '#f0f9ff' : '#fff',
          border: data.m2_review?.status === 'failed' ? '1px solid #fecaca' :
                  data.m2_review?.status === 'success' ? '1px solid #bae6fd' : '1px solid #e2e8f0',
        }}
      >
        <div style={{ ...sectionTitleStyle, display: 'flex', alignItems: 'center', gap: 8 }}>
          M2 decision review (LLM-enhanced)
          {data.m2_review?.status === 'success' && <span style={{ color: '#16a34a' }}>✓</span>}
          {data.m2_review?.status === 'failed' && <span style={{ color: '#dc2626' }}>✗</span>}
          {data.m2_review?.status === 'skipped' && <span style={{ color: '#94a3b8' }}>Skipped</span>}
          {data.m2_review?.status === 'pending' && <span style={{ color: '#f59e0b' }}>⏳</span>}
        </div>

        {data.m2_review?.status === 'skipped' && data.m2_review.skip_reason && (
          <div style={{ color: '#64748b', marginBottom: 8, fontSize: 12 }}>
            Skip Reason: {data.m2_review.skip_reason}
          </div>
        )}

        {data.m2_review?.status === 'success' && (
          <>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
              <MetricCard label="Duration" value={data.m2_review.duration_ms ? `${data.m2_review.duration_ms}ms` : '—'} />
              <MetricCard label="Bullets" value={data.m2_review.bullets_count} />
              <MetricCard label="Bias Insights" value={data.m2_review.bias_insights_count} />
            </div>

            {data.m2_review.headline && (
              <div
                style={{
                  marginTop: 12,
                  padding: 8,
                  background: '#f0f9ff',
                  border: '1px solid #bae6fd',
                  borderRadius: 4,
                  fontSize: 12,
                }}
              >
                <strong>Headline:</strong> {data.m2_review.headline}
              </div>
            )}

            <details style={{ marginTop: 12 }}>
              <summary style={{ cursor: 'pointer', fontSize: 11, color: '#64748b' }}>
                View Raw M2 Response
              </summary>
              <div style={{ marginTop: 8 }}>
                <JsonViewer data={data.m2_review.raw} maxHeight={300} />
              </div>
            </details>
          </>
        )}

        {data.m2_review?.status === 'failed' && (
          <div
            style={{
              color: '#dc2626',
              padding: 8,
              background: '#fef2f2',
              borderRadius: 4,
              fontSize: 12,
            }}
          >
            Error: {data.m2_review.error ?? 'Unknown error'}
          </div>
        )}

        {data.m2_review?.status === 'pending' && (
          <div style={{ color: '#f59e0b', fontSize: 12 }}>
            M2 Review request in progress...
          </div>
        )}

        {!data.m2_review && (
          <div style={{ color: '#94a3b8', fontSize: 12 }}>
            M2 Review not available (requires analysis completion)
          </div>
        )}
      </div>

      {/* No data placeholder */}
      {!data.hasData && (
        <div
          style={{
            padding: 24,
            textAlign: 'center',
            color: '#64748b',
            fontSize: 12,
          }}
        >
          No pipeline data available. Run an analysis to see processing stages.
        </div>
      )}
    </div>
  )
}

export default PipelineTab
