/**
 * SummaryTab Component
 *
 * At-a-glance health check for Debug Panel V2.
 * Shows KPIs, service chain, quick stats, and graph validation.
 */

import { useState, useMemo, CSSProperties } from 'react'
import { KpiCard, ServiceChain, type ChainNode, type ChainNodeStatus, type KpiStatus, type PipelineStepData } from '../components'
import type { DebugData, ValidationIssue } from '../hooks/useDebugData'
import { formatDuration } from '../utils'
import { getErrorInfo } from '../constants/errorCodes'

type SeverityFilter = 'all' | 'error' | 'warning' | 'info'

// Severity icon and color mapping
const SEVERITY_CONFIG = {
  error: { icon: '●', bg: '#fef2f2', border: '#fecaca', text: '#dc2626' },
  warning: { icon: '⚠', bg: '#fffbeb', border: '#fde68a', text: '#d97706' },
  info: { icon: 'ℹ', bg: '#eff6ff', border: '#bfdbfe', text: '#2563eb' },
} as const

// Human-readable explanations for validation codes
const VALIDATION_EXPLANATIONS: Record<string, string> = {
  COEFFICIENT_REPAIRED: 'Edge strength was auto-adjusted to valid range',
  NORMALIZATION_WARNING: 'Option node filtered before analysis (expected behaviour)',
  GRAPH_DISCONNECTED: "Some nodes aren't connected to the goal — they won't affect results",
  STRENGTH_OUT_OF_RANGE: 'Edge strength outside [-1, +1] detected',
  BIDIRECTIONAL_EDGE: 'Two-way causal link found — review direction',
  UNIFORM_STRENGTHS: 'All edges have identical strength — may indicate prompt issue',
  MISSING_GOAL: 'No goal node found in the graph',
  ORPHAN_NODE: 'Node has no connections',
  CYCLE_DETECTED: 'Circular dependency found in the graph',
  INVALID_EDGE: 'Edge connects incompatible node types',
}

// Human-readable explanations for CEE repair types
const REPAIR_TYPE_EXPLANATIONS: Record<string, string> = {
  coefficient_normalization: 'Edge strengths normalized to [-1, +1]',
  orphan_removal: 'Disconnected nodes removed from graph',
  cycle_breaking: 'Circular dependencies resolved',
  bidirectional_resolution: 'Two-way edges converted to single direction',
  missing_goal_addition: 'Goal node added to graph structure',
  invalid_edge_removal: 'Invalid connections removed',
  strength_balancing: 'Edge weights rebalanced for consistency',
  graph_regeneration: 'Graph fully regenerated by LLM',
}

/**
 * Individual validation issue card
 */
function ValidationIssueCard({ issue }: { issue: ValidationIssue }) {
  // Fallback to 'info' config for unknown severity values
  const config = SEVERITY_CONFIG[issue.severity as keyof typeof SEVERITY_CONFIG] ?? SEVERITY_CONFIG.info
  // Get human-readable explanation for the code, fallback to message
  const explanation = VALIDATION_EXPLANATIONS[issue.code]

  return (
    <div
      style={{
        padding: '8px 12px',
        background: config.bg,
        border: `1px solid ${config.border}`,
        borderRadius: 6,
        fontSize: 12,
      }}
    >
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 8 }}>
        <span style={{ color: config.text, flexShrink: 0 }}>{config.icon}</span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 2 }}>
            <span
              style={{
                fontFamily: 'monospace',
                fontWeight: 600,
                color: config.text,
                fontSize: 11,
              }}
            >
              {issue.code}
            </span>
            <span
              style={{
                fontSize: 10,
                padding: '1px 4px',
                borderRadius: 3,
                background: issue.source === 'isl' ? '#e0e7ff' : '#f3e8ff',
                color: issue.source === 'isl' ? '#4338ca' : '#7c3aed',
              }}
            >
              {issue.source.toUpperCase()}
            </span>
          </div>
          {/* Plain-English explanation of the code */}
          {explanation && (
            <div style={{ color: '#475569', lineHeight: 1.4, marginBottom: 4 }}>
              {explanation}
            </div>
          )}
          <div style={{ color: '#374151', lineHeight: 1.4 }}>{issue.message}</div>
          {issue.suggestion && (
            <div style={{ color: '#6b7280', marginTop: 4, fontStyle: 'italic' }}>
              💡 {issue.suggestion}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export interface SummaryTabProps {
  /** Debug data from useDebugData hook */
  data: DebugData
  /** Navigate to Data Flow tab */
  onNavigateToDataFlow?: () => void
  /** Navigate to Pipeline tab */
  onNavigateToPipeline?: () => void
  /** Navigate to Raw tab */
  onNavigateToRaw?: () => void
}

function formatNodeCounts(connectivity: DebugData['pipeline']['connectivity']): string {
  if (!connectivity) return '—'
  const parts: string[] = []
  if (connectivity.decision_count > 0) parts.push(`${connectivity.decision_count} decision`)
  if (connectivity.option_count > 0) parts.push(`${connectivity.option_count} options`)
  if (connectivity.factor_count > 0) parts.push(`${connectivity.factor_count} factors`)
  if (connectivity.goal_count > 0) parts.push(`${connectivity.goal_count} goal`)
  return parts.join(', ') || 'No nodes'
}

function deriveAnalysisStatus(data: DebugData): { status: KpiStatus; label: string } {
  if (data.overall.status === 'error') return { status: 'error', label: 'Error' }
  if (data.overall.status === 'pending') return { status: 'warn', label: 'Pending' }
  if (!data.hasData) return { status: 'neutral', label: 'No Data' }
  return { status: 'ok', label: 'Complete' }
}

function countIssues(gates: DebugData['gates']): number {
  // Only count 'fail' status as issues - 'warn' is for UI demotion, not blocking issues
  return gates.filter((g) => g.status === 'fail').length
}

/**
 * Transform CEE observability data into pipeline steps for Service Chain display.
 * Uses timestamps for proper chronological ordering when available.
 */
function buildCEEPipelineSteps(data: DebugData): PipelineStepData[] {
  const obs = data.cee_observability
  if (!obs) return []

  const llmCalls = obs.llm_calls ?? []
  const validationAttempts = obs.validation?.attempt_records ?? []

  // Build unified list with timestamps for sorting
  type TimestampedStep = PipelineStepData & { timestamp: number }
  const allSteps: TimestampedStep[] = []

  // Add LLM calls with their started_at timestamps
  llmCalls.forEach((call) => {
    const timestamp = call.started_at ? new Date(call.started_at).getTime() : 0
    allSteps.push({
      step: call.step,
      model: call.model,
      latency_ms: call.latency_ms,
      success: call.success,
      error: call.error,
      tokens: call.tokens,
      isRepair: call.step === 'repair_graph',
      timestamp,
    })
  })

  // Add validation attempts with their timestamps
  validationAttempts.forEach((attempt, i) => {
    const timestamp = attempt.timestamp ? new Date(attempt.timestamp).getTime() : 0
    allSteps.push({
      step: `validate`,
      latency_ms: attempt.latency_ms,
      success: attempt.passed,
      validationFailure: !attempt.passed ? {
        rulesChecked: attempt.rules_checked,
        rulesFailed: attempt.rules_failed,
      } : undefined,
      timestamp,
    })
  })

  // Sort by timestamp (chronological order)
  // If timestamps are missing (0), maintain relative order by type: LLM calls first per attempt
  allSteps.sort((a, b) => {
    // If both have valid timestamps, sort chronologically
    if (a.timestamp > 0 && b.timestamp > 0) {
      return a.timestamp - b.timestamp
    }
    // If neither has timestamps, keep original insertion order
    return 0
  })

  // Strip timestamp from output (not part of PipelineStepData interface)
  return allSteps.map(({ timestamp, ...step }) => step)

  return steps
}

export function SummaryTab({
  data,
  onNavigateToDataFlow,
  onNavigateToPipeline,
  onNavigateToRaw,
}: SummaryTabProps) {
  // Build pipeline steps from CEE observability
  const ceePipelineSteps = useMemo(() => buildCEEPipelineSteps(data), [data])

  // Build service chain nodes with downstream failure handling
  const chainNodes = useMemo((): ChainNode[] => {
    const nodes: ChainNode[] = []
    let previousFailed = false

    // UI node (always present)
    nodes.push({
      name: 'UI',
      duration_ms: null,
      status: 'success',
    })

    // CEE (with expandable pipeline steps)
    if (data.services.cee) {
      const failed = !data.services.cee.success
      const hasPipelineSteps = ceePipelineSteps.length > 0

      nodes.push({
        name: 'CEE',
        duration_ms: data.services.cee.duration_ms,
        status: previousFailed ? 'skipped' : failed ? 'error' : 'success',
        statusCode: previousFailed ? null : data.services.cee.status,
        onClick: hasPipelineSteps ? undefined : onNavigateToDataFlow,
        pipelineSteps: previousFailed ? undefined : ceePipelineSteps,
        stepCount: data.cee_observability?.totals?.total_llm_calls,
      })
      if (failed) previousFailed = true
    }

    // PLoT
    if (data.services.plot || previousFailed) {
      const plotData = data.services.plot
      nodes.push({
        name: 'PLoT',
        duration_ms: previousFailed ? null : plotData?.duration_ms ?? null,
        status: previousFailed ? 'skipped' : plotData?.success ? 'success' : plotData?.error ? 'error' : 'pending',
        statusCode: previousFailed ? null : plotData?.status,
        onClick: onNavigateToDataFlow,
      })
      if (plotData && !plotData.success) previousFailed = true
    }

    // ISL
    if (data.services.isl || data.services.plot || previousFailed) {
      const islData = data.services.isl
      nodes.push({
        name: 'ISL',
        duration_ms: previousFailed ? null : islData?.duration_ms ?? null,
        status: previousFailed ? 'skipped' : islData?.success ? 'success' : islData?.error ? 'error' : 'unavailable',
        statusCode: previousFailed ? null : islData?.status,
        onClick: onNavigateToDataFlow,
      })
      if (islData && !islData.success) previousFailed = true
    }

    // M2 Review (LLM-Enhanced Decision Review)
    // Show M2 node when: extraction succeeded OR payload was captured (fallback for extraction failures)
    const hasM2Payload = data.payloads.m2_request !== undefined || data.payloads.m2_response !== undefined
    if (data.m2_review || hasM2Payload) {
      const m2Status: ChainNodeStatus =
        previousFailed ? 'skipped' :
        !data.m2_review ? 'unavailable' : // Payload exists but extraction failed
        data.m2_review.status === 'success' ? 'success' :
        data.m2_review.status === 'failed' ? 'error' :
        data.m2_review.status === 'skipped' ? 'skipped' :
        data.m2_review.status === 'pending' ? 'pending' : 'unavailable'

      nodes.push({
        name: 'M2 Review',
        duration_ms: previousFailed ? null : data.m2_review?.duration_ms ?? null,
        status: m2Status,
        statusCode: null,
        onClick: onNavigateToPipeline,
      })
    }

    return nodes
  }, [data.services, data.cee_observability, data.m2_review, data.payloads, ceePipelineSteps, onNavigateToDataFlow, onNavigateToPipeline])

  // Validation filter state
  const [severityFilter, setSeverityFilter] = useState<SeverityFilter>('all')
  // Auto-expand validation section if there are errors or warnings (but not for info-only)
  const [validationExpanded, setValidationExpanded] = useState(() =>
    data.validation.summary.errors > 0 || data.validation.summary.warnings > 0
  )

  // Filtered validation issues
  const filteredIssues = useMemo(() => {
    if (severityFilter === 'all') return data.validation.issues
    return data.validation.issues.filter(issue => issue.severity === severityFilter)
  }, [data.validation.issues, severityFilter])

  // KPI values
  const analysisKpi = deriveAnalysisStatus(data)
  const issueCount = countIssues(data.gates)

  // Token usage
  const tokenUsage = data.pipeline.llm_metadata?.token_usage
  const tokenDisplay = tokenUsage
    ? `${tokenUsage.prompt_tokens ?? 0} → ${tokenUsage.completion_tokens ?? 0}`
    : '—'

  const sectionStyle: CSSProperties = {
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: 12,
  }

  const sectionTitleStyle: CSSProperties = {
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: '#64748b',
    marginBottom: 12,
  }

  // Format temperature: show value if available, "N/A" if missing
  const temperature = data.pipeline.llm_metadata?.temperature
  const temperatureDisplay = temperature != null && !Number.isNaN(temperature)
    ? temperature
    : 'N/A'

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, padding: 12 }}>
      {/* Error Banner */}
      {data.error && (() => {
        const errorInfo = getErrorInfo(data.error.code)
        return (
          <div
            style={{
              background: '#fef2f2',
              border: '1px solid #fecaca',
              borderRadius: 8,
              padding: 12,
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
              <span
                style={{
                  color: '#dc2626',
                  fontFamily: 'monospace',
                  fontSize: 13,
                  fontWeight: 500,
                }}
              >
                {data.error.code}
              </span>
              <span style={{ color: '#991b1b', fontSize: 13 }}>{data.error.message}</span>
              <span style={{ color: '#f87171', fontSize: 12 }}>({data.error.status})</span>
            </div>
            <div style={{ color: '#dc2626', fontSize: 12, marginTop: 4 }}>
              Duration: {formatDuration(data.error.duration_ms)}
              {data.error.retryable && ' • Retryable'}
            </div>
            {errorInfo && (
              <div style={{ fontSize: 12, marginTop: 8, paddingTop: 8, borderTop: '1px solid #fecaca' }}>
                <div style={{ color: '#b91c1c' }}>{errorInfo.description}</div>
                <div style={{ color: '#dc2626', marginTop: 2 }}>
                  <strong>Action:</strong> {errorInfo.action}
                </div>
              </div>
            )}
          </div>
        )
      })()}

      {/* Row 1: KPI Cards */}
      <div style={sectionStyle}>
        <div style={sectionTitleStyle}>Health Overview</div>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
            gap: 12,
          }}
        >
          <KpiCard
            label="Graph Stats"
            value={formatNodeCounts(data.pipeline.connectivity)}
            status="neutral"
            onClick={onNavigateToPipeline}
            tooltip="Click to view pipeline details"
            compact
          />
          <KpiCard
            label="Analysis"
            value={analysisKpi.label}
            status={analysisKpi.status}
            onClick={onNavigateToDataFlow}
            tooltip="Click to view data flow"
            compact
          />
          {/* Winner card - only show when there's a winning option */}
          {data.winningOption && (
            <KpiCard
              label="Winner"
              value={`${data.winningOption.label || data.winningOption.id || 'Unknown'} (${Number.isFinite(data.winningOption.win_probability) ? data.winningOption.win_probability.toFixed(0) : '—'}%)`}
              status={data.winningOption.is_close_race ? 'warn' : 'ok'}
              tooltip={data.winningOption.is_close_race && data.winningOption.runner_up
                ? `Close race vs ${data.winningOption.runner_up.label || data.winningOption.runner_up.id || 'Unknown'} (${Number.isFinite(data.winningOption.runner_up.win_probability) ? data.winningOption.runner_up.win_probability.toFixed(0) : '—'}%)`
                : 'Clear winner'}
              compact
            />
          )}
          <KpiCard
            label="Robustness"
            value={data.robustness.context_label}
            status={
              data.robustness.status === 'pass' ? 'ok' :
              data.robustness.status === 'warn' ? 'warn' :
              data.robustness.status === 'fail' ? 'error' : 'neutral'
            }
            onClick={onNavigateToRaw}
            tooltip={data.robustness.description}
            compact
          />
          <KpiCard
            label="Issues"
            value={issueCount > 0 ? String(issueCount) : 'None'}
            status={issueCount > 0 ? 'warn' : 'ok'}
            onClick={onNavigateToDataFlow}
            tooltip={issueCount > 0 ? 'Click to investigate' : 'All gates passing'}
            compact
          />
        </div>
      </div>

      {/* Row 2: Winning Option (if available) */}
      {data.winningOption && (
        <div style={sectionStyle}>
          <div style={sectionTitleStyle}>Recommendation</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            <div style={{ fontSize: 14, fontWeight: 600, color: '#1e293b' }}>
              Winner: {data.winningOption.label}
            </div>
            <div style={{ fontSize: 13, color: '#475569' }}>
              {data.winningOption.win_probability.toFixed(0)}% confidence
              {data.winningOption.is_close_race && data.winningOption.runner_up && (
                <span style={{ color: '#64748b' }}>
                  {' '}vs {data.winningOption.runner_up.label} at {data.winningOption.runner_up.win_probability.toFixed(0)}%
                </span>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Row 3: Service Chain */}
      <div style={sectionStyle}>
        <div style={sectionTitleStyle}>Service Chain</div>
        <ServiceChain nodes={chainNodes} />
      </div>

      {/* Row 3: Graph Validation */}
      {data.hasData && (
        <div style={sectionStyle}>
          {/* Header with title, severity counts, and filter */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <button
                onClick={() => setValidationExpanded(!validationExpanded)}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: 'pointer',
                  padding: 0,
                  fontSize: 12,
                  color: '#64748b',
                }}
                aria-label={validationExpanded ? 'Collapse validation' : 'Expand validation'}
              >
                {validationExpanded ? '▼' : '▶'}
              </button>
              <span style={sectionTitleStyle as CSSProperties & { marginBottom: 0 }}>
                Graph Validation
              </span>
              {/* Severity counts badge */}
              <div style={{ display: 'flex', gap: 8, marginLeft: 8 }}>
                {data.validation.summary.errors > 0 && (
                  <span style={{
                    fontSize: 11,
                    padding: '2px 6px',
                    borderRadius: 4,
                    background: '#fef2f2',
                    color: '#dc2626',
                    fontWeight: 600,
                  }}>
                    ● {data.validation.summary.errors} Error{data.validation.summary.errors !== 1 ? 's' : ''}
                  </span>
                )}
                {data.validation.summary.warnings > 0 && (
                  <span style={{
                    fontSize: 11,
                    padding: '2px 6px',
                    borderRadius: 4,
                    background: '#fffbeb',
                    color: '#d97706',
                    fontWeight: 600,
                  }}>
                    ⚠ {data.validation.summary.warnings} Warning{data.validation.summary.warnings !== 1 ? 's' : ''}
                  </span>
                )}
                {data.validation.summary.info > 0 && (
                  <span style={{
                    fontSize: 11,
                    padding: '2px 6px',
                    borderRadius: 4,
                    background: '#eff6ff',
                    color: '#2563eb',
                    fontWeight: 600,
                  }}>
                    ℹ {data.validation.summary.info} Info
                  </span>
                )}
                {data.validation.issues.length === 0 && (
                  <span style={{
                    fontSize: 11,
                    padding: '2px 6px',
                    borderRadius: 4,
                    background: '#f0fdf4',
                    color: '#16a34a',
                    fontWeight: 600,
                  }}>
                    ✓ No Issues
                  </span>
                )}
                {/* CEE Repair badges */}
                {data.cee_observability?.validation?.repairs_triggered && (
                  <span style={{
                    fontSize: 11,
                    padding: '2px 6px',
                    borderRadius: 4,
                    background: '#fffbeb',
                    color: '#d97706',
                    fontWeight: 600,
                  }}>
                    ⚡ {data.cee_observability.validation.repair_types.length} Repair Type{data.cee_observability.validation.repair_types.length !== 1 ? 's' : ''}
                  </span>
                )}
                {data.cee_observability?.validation?.retry_triggered && (
                  <span style={{
                    fontSize: 11,
                    padding: '2px 6px',
                    borderRadius: 4,
                    background: '#fef2f2',
                    color: '#dc2626',
                    fontWeight: 600,
                  }}>
                    🔄 Retry
                  </span>
                )}
              </div>
            </div>
            {/* Severity filter dropdown */}
            {data.validation.issues.length > 0 && validationExpanded && (
              <select
                value={severityFilter}
                onChange={(e) => setSeverityFilter(e.target.value as SeverityFilter)}
                style={{
                  fontSize: 11,
                  padding: '4px 8px',
                  borderRadius: 4,
                  border: '1px solid #e2e8f0',
                  background: '#fff',
                  cursor: 'pointer',
                }}
              >
                <option value="all">All</option>
                <option value="error">Errors Only</option>
                <option value="warning">Warnings Only</option>
                <option value="info">Info Only</option>
              </select>
            )}
          </div>

          {/* CEE Validation Details (when repairs were triggered) */}
          {validationExpanded && data.cee_observability?.validation && (
            <div style={{
              marginBottom: 12,
              padding: 12,
              background: data.cee_observability.validation.repairs_triggered ? '#fffbeb' : '#f0fdf4',
              border: `1px solid ${data.cee_observability.validation.repairs_triggered ? '#fde68a' : '#86efac'}`,
              borderRadius: 6,
              fontSize: 12,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                <span style={{
                  fontWeight: 600,
                  color: data.cee_observability.validation.passed ? '#16a34a' : '#dc2626',
                }}>
                  {data.cee_observability.validation.passed ? '✓' : '✗'} CEE Validation
                </span>
                <span style={{ color: '#6b7280', fontSize: 11 }}>
                  {data.cee_observability.validation.attempts} attempt{data.cee_observability.validation.attempts !== 1 ? 's' : ''}
                  {' • '}
                  {data.cee_observability.validation.total_rules_checked} rules checked
                </span>
              </div>

              {/* Repair types with explanations */}
              {data.cee_observability.validation.repairs_triggered && data.cee_observability.validation.repair_types.length > 0 && (
                <div style={{ marginTop: 8 }}>
                  <div style={{ fontSize: 11, fontWeight: 600, color: '#92400e', marginBottom: 4 }}>
                    ⚡ Repairs Applied:
                  </div>
                  <ul style={{ margin: 0, paddingLeft: 20, fontSize: 11, color: '#78716c' }}>
                    {data.cee_observability.validation.repair_types.map((type, i) => (
                      <li key={i}>
                        <strong>{type}:</strong> {REPAIR_TYPE_EXPLANATIONS[type] ?? 'Automated fix applied'}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Failed rules (if validation failed) */}
              {data.cee_observability.validation.failed_rules.length > 0 && (
                <div style={{ marginTop: 8 }}>
                  <div style={{ fontSize: 11, fontWeight: 600, color: '#dc2626', marginBottom: 4 }}>
                    Failed Rules:
                  </div>
                  <ul style={{ margin: 0, paddingLeft: 20, fontSize: 11, color: '#6b7280' }}>
                    {data.cee_observability.validation.failed_rules.map((rule, i) => (
                      <li key={i}>{rule}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {/* Issues list */}
          {validationExpanded && filteredIssues.length > 0 && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {filteredIssues.map((issue) => (
                <ValidationIssueCard key={issue.id} issue={issue} />
              ))}
            </div>
          )}

          {/* Empty state when filtered */}
          {validationExpanded && filteredIssues.length === 0 && data.validation.issues.length > 0 && (
            <div style={{ fontSize: 12, color: '#64748b', fontStyle: 'italic' }}>
              No {severityFilter} issues found
            </div>
          )}
        </div>
      )}

      {/* Row 4: Quick Stats - Dense Row */}
      <div style={sectionStyle}>
        <div style={sectionTitleStyle}>Quick Stats</div>
        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: '8px 24px',
            fontSize: 13,
            color: '#475569',
          }}
        >
          <span>
            <strong style={{ color: '#1e293b' }}>Model:</strong>{' '}
            {data.pipeline.llm_metadata?.model ?? '—'}
          </span>
          {data.pipeline.llm_metadata?.prompt_version && (() => {
            const diagnostics = data.pipeline.llm_metadata.prompt_diagnostics
            const tooltipParts = [data.pipeline.llm_metadata.prompt_version]
            if (data.pipeline.llm_metadata.prompt_hash) {
              tooltipParts.push(`Hash: ${data.pipeline.llm_metadata.prompt_hash}`)
            }
            if (diagnostics?.cache_status) {
              tooltipParts.push(`Cache: ${diagnostics.cache_status}${diagnostics.cache_age_ms != null ? ` (${diagnostics.cache_age_ms}ms)` : ''}`)
            }
            if (diagnostics?.use_staging_mode != null) {
              tooltipParts.push(`Staging: ${diagnostics.use_staging_mode ? 'yes' : 'no'}`)
            }
            if (diagnostics?.instance_id) {
              tooltipParts.push(`Instance: ${diagnostics.instance_id}`)
            }
            return (
              <span title={tooltipParts.join('\n')}>
                <strong style={{ color: '#1e293b' }}>Prompt:</strong>{' '}
                {data.pipeline.llm_metadata.prompt_version}
              </span>
            )
          })()}
          <span>
            <strong style={{ color: '#1e293b' }}>Tokens:</strong> {tokenDisplay}
          </span>
          <span>
            <strong style={{ color: '#1e293b' }}>Duration:</strong>{' '}
            {formatDuration(data.overall.total_duration_ms)}
          </span>
          <span>
            <strong style={{ color: '#1e293b' }}>Edges:</strong>{' '}
            {data.pipeline.connectivity?.edge_count ?? '—'}
          </span>
          <span>
            <strong style={{ color: '#1e293b' }}>Temp:</strong> {temperatureDisplay}
          </span>
          {data.overall.request_id && (
            <span
              style={{ fontFamily: 'monospace', fontSize: 12 }}
              title={data.overall.request_id}
            >
              {data.overall.request_id.slice(0, 8)}...
            </span>
          )}
          {/* CEE Observability Stats */}
          {data.cee_observability?.totals && (
            <>
              <span>
                <strong style={{ color: '#1e293b' }}>LLM Calls:</strong>{' '}
                {data.cee_observability.totals.total_llm_calls}
              </span>
              <span title={`Input: ${data.cee_observability.totals.total_tokens.input.toLocaleString()} • Output: ${data.cee_observability.totals.total_tokens.output.toLocaleString()}`}>
                <strong style={{ color: '#1e293b' }}>CEE Tokens:</strong>{' '}
                {data.cee_observability.totals.total_tokens.total.toLocaleString()}
              </span>
            </>
          )}
          {data.cee_observability?.validation?.repairs_triggered && (
            <span style={{ color: '#d97706' }}>
              <strong style={{ color: '#92400e' }}>Repair Types:</strong>{' '}
              {data.cee_observability.validation.repair_types.length}
            </span>
          )}
          {data.cee_observability?.validation?.retry_triggered && (
            <span style={{ color: '#dc2626' }}>
              <strong style={{ color: '#991b1b' }}>Retries:</strong>{' '}
              {data.cee_observability.validation.attempts - 1}
            </span>
          )}
          {/* Validation attempts (show when > 1, indicates re-validation after repair) */}
          {data.cee_observability?.validation && data.cee_observability.validation.attempts > 1 && (
            <span>
              <strong style={{ color: '#1e293b' }}>Validation:</strong>{' '}
              {data.cee_observability.validation.attempts} attempts
            </span>
          )}
        </div>

        {/* Builds Row */}
        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: '8px 16px',
            fontSize: 12,
            color: '#64748b',
            marginTop: 8,
            fontFamily: 'monospace',
          }}
        >
          <span>
            <strong style={{ color: '#475569', fontFamily: 'inherit' }}>Builds:</strong>
          </span>
          <span>UI {data.builds.ui ?? '—'}</span>
          <span>•</span>
          <span>PLoT {data.builds.plot ?? '—'}</span>
          <span>•</span>
          <span>CEE {data.builds.cee ?? '—'}</span>
          <span>•</span>
          <span>ISL {data.builds.isl ?? '—'}</span>
        </div>
      </div>

      {/* No data placeholder */}
      {!data.hasData && (
        <div
          style={{
            padding: 24,
            textAlign: 'center',
            color: '#64748b',
            fontSize: 12,
          }}
        >
          No debug data available. Run an analysis to see results.
        </div>
      )}
    </div>
  )
}

export default SummaryTab
