/**
 * Request ID Types
 *
 * CEE uses SafeRequestId format: 1-64 chars, [A-Za-z0-9._-]
 * Server may regenerate request_id if original was unsafe.
 *
 * Used by:
 * - useAsk for request tracing
 * - Results store for unified tracing
 * - Debug panels for troubleshooting
 */

// =============================================================================
// Constants
// =============================================================================

/**
 * SafeRequestId pattern: 1-64 chars matching [A-Za-z0-9._-]
 */
export const SAFE_REQUEST_ID_PATTERN = /^[A-Za-z0-9._-]{1,64}$/

// =============================================================================
// Types
// =============================================================================

/**
 * Request trace containing both client and server IDs
 */
export interface RequestTrace {
  /** ID generated by client (UUID v4) */
  clientRequestId: string
  /** ID returned by server (may differ from client if original was unsafe) */
  serverRequestId: string
}

/**
 * Ask record for results store
 */
export interface AskRecord {
  /** Unique record ID */
  id: string
  /** Client-generated request ID */
  clientRequestId: string
  /** Server-returned request ID */
  serverRequestId: string
  /** ISO timestamp of request */
  timestamp: string
  /** User's message */
  message: string
  /** Server response */
  response: AskResponseBase
}

/**
 * Base ask response structure (for typing)
 */
export interface AskResponseBase {
  request_id: string
  message: string
  model_actions?: unknown[]
  highlights?: unknown[]
  follow_up_question?: string
  why?: unknown[]
  attribution?: unknown
}

// =============================================================================
// Validation Functions
// =============================================================================

/**
 * Check if a value is a valid SafeRequestId
 */
export function isValidRequestId(id: unknown): id is string {
  return typeof id === 'string' && SAFE_REQUEST_ID_PATTERN.test(id)
}

/**
 * Generate a safe request ID (UUID v4)
 */
export function generateRequestId(): string {
  return crypto.randomUUID()
}

/**
 * Sanitize a request ID to SafeRequestId format
 * Replaces invalid characters and truncates to 64 chars
 */
export function sanitizeRequestId(id: string): string {
  // Replace invalid characters with underscores
  const sanitized = id.replace(/[^A-Za-z0-9._-]/g, '_')
  // Truncate to 64 chars
  return sanitized.slice(0, 64)
}

/**
 * Extract request ID from response, preferring body over header
 *
 * @param body - Response body (should contain request_id)
 * @param headers - Response headers (may contain X-CEE-Request-ID)
 * @returns Server request ID or undefined
 */
export function extractServerRequestId(
  body: unknown,
  headers?: Headers
): string | undefined {
  // Body is source of truth
  if (body && typeof body === 'object' && 'request_id' in body) {
    const bodyId = (body as { request_id: unknown }).request_id
    if (typeof bodyId === 'string' && bodyId.length > 0) {
      return bodyId
    }
  }

  // Fall back to header
  if (headers) {
    const headerId = headers.get('X-CEE-Request-ID')
    if (headerId && headerId.length > 0) {
      return headerId
    }
  }

  return undefined
}
