import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Minus, Plus, RefreshCw } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import * as scenarioService from '../services/scenarioService'
import { fetchScenarioGraph, type ScenarioGraphResult } from '../adapters/cee/scenarioGraph'
import { isReadTerminalRunState, leaderClaimWithholdingReason } from '../canvas/hydrate/applyScenarioAnalysisRead'
import { scienceChangeText } from '../components/science/ScienceQuantity'
import type { ScenarioListItem, ScenarioRow } from '../types/scenario'
import { typography } from '../styles/typography'

type Item = { id: string; label?: string; data?: Record<string, unknown>; source?: string; target?: string; from?: string; to?: string }
type Graph = { nodes: Item[]; edges: Item[] }
type Diff = { added: Item[]; removed: Item[]; changed: Array<{ left: Item; right: Item; matchedByName: boolean }> }
const graphOf = (row: ScenarioRow): Graph => { const graph = row.graph as { nodes?: unknown; edges?: unknown } | null; return { nodes: Array.isArray(graph?.nodes) ? graph.nodes as Item[] : [], edges: Array.isArray(graph?.edges) ? graph.edges as Item[] : [] } }
const value = (item: Item, key: string): unknown => item.data?.[key] ?? item[key as keyof Item]
const label = (item: Item): string => typeof value(item, 'label') === 'string' ? value(item, 'label') as string : 'Unnamed model item'
const nameKey = (item: Item): string => `${String(value(item, 'kind') ?? '')}:${label(item).trim().toLowerCase()}`
function diffItems(left: Item[], right: Item[]): Diff { const byId = new Map(right.map(item => [item.id, item])); const remaining = new Set(right); const removed: Item[] = []; const changed: Diff['changed'] = []; left.forEach(item => { const match = byId.get(item.id); if (match) { remaining.delete(match); if (JSON.stringify(item) !== JSON.stringify(match)) changed.push({ left: item, right: match, matchedByName: false }) } else removed.push(item) }); removed.slice().forEach(item => { const match = [...remaining].find(candidate => nameKey(candidate) === nameKey(item)); if (match) { remaining.delete(match); removed.splice(removed.indexOf(item), 1); changed.push({ left: item, right: match, matchedByName: true }) } }); return { added: [...remaining], removed, changed } }
const diffGraph = (a: Graph, b: Graph) => ({ nodes: diffItems(a.nodes, b.nodes), edges: diffItems(a.edges, b.edges) })
function resultFromRead(read: ScenarioGraphResult): string | null { if (read.status !== 'graph' || !read.analysisState || !isReadTerminalRunState(read.analysisState.run_state.kind) || read.analysisState.run_state.kind !== 'complete_current' || leaderClaimWithholdingReason(read.analysisState)) return null; const result = read.analysisResult as { summary?: unknown; leading_option_id?: unknown; enrichment?: { option_comparison?: Array<{ id?: unknown; label?: unknown }> } } | null; if (!result || typeof result.summary !== 'string' || typeof result.leading_option_id !== 'string') return null; const option = result.enrichment?.option_comparison?.find(item => item.id === result.leading_option_id); return option && typeof option.label === 'string' ? `${option.label}: ${result.summary}` : null }
function edgeLabel(item: Item, graph: Graph): string { const source = item.source ?? item.from; const target = item.target ?? item.to; return `${label(graph.nodes.find(node => node.id === source) ?? { id: '', label: source })} → ${label(graph.nodes.find(node => node.id === target) ?? { id: '', label: target })}` }
function changedWords(left: Item, right: Item, graph: Graph, edge: boolean): string { if (edge) { const before = value(left, 'strength'); const after = value(right, 'strength'); const n = (x: unknown) => typeof x === 'number' ? x : x && typeof x === 'object' && typeof (x as { mean?: unknown }).mean === 'number' ? (x as { mean: number }).mean : undefined; const a = n(before); const b = n(after); if (a !== undefined && b !== undefined && a !== b) return `${edgeLabel(left, graph)} changed strength: ${scienceChangeText('strength', a, b) ?? 'changed'}`; return `${edgeLabel(left, graph)} changed` } return `${label(left)} changed` }
function Side({ row, result, failed }: { row: ScenarioRow; result: string | null; failed: boolean }) { const graph = graphOf(row); return <section className="rounded-[20px] bg-panel shadow-1 p-5" data-testid="comparison-side"><h2 className={`${typography.h3} text-text-header`}>{row.title || 'Untitled scenario'}</h2><p className={`${typography.caption} text-text-light mt-1`}>{graph.nodes.length} model items, {graph.edges.length} links</p><h3 className={`${typography.label} text-text-header mt-5 border-t border-border-subtle pt-4`}>Current result</h3><p className={`${typography.body} text-text-body mt-2`} data-testid="comparison-result">{failed ? "Couldn't load this scenario's result" : result ?? 'No current result for this scenario yet. Open it and run the analysis.'}</p></section> }
function DiffGroup({ label: heading, diff, graph, edge }: { label: string; diff: Diff; graph: Graph; edge: boolean }) { return <div><h3 className={`${typography.label} text-text-header`}>{heading}</h3><div className="mt-2 space-y-1">{diff.added.map(item => <p key={`a-${item.id}`}><Plus className="inline w-3 h-3" /> Added: {edge ? edgeLabel(item, graph) : label(item)}</p>)}{diff.removed.map(item => <p key={`r-${item.id}`}><Minus className="inline w-3 h-3" /> Removed: {edge ? edgeLabel(item, graph) : label(item)}</p>)}{diff.changed.map(item => <p key={`c-${item.left.id}-${item.right.id}`}><RefreshCw className="inline w-3 h-3" /> {changedWords(item.left, item.right, graph, edge)}{item.matchedByName ? ' (matched by name)' : ''}</p>)}{!diff.added.length && !diff.removed.length && !diff.changed.length && <p>No differences.</p>}</div></div> }
export default function ScenarioComparePage() { const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const { user } = useAuth(); const [left, setLeft] = useState<ScenarioRow | null>(null); const [right, setRight] = useState<ScenarioRow | null>(null); const [items, setItems] = useState<ScenarioListItem[]>([]); const [results, setResults] = useState<Record<string, string | null>>({}); const [failed, setFailed] = useState<Record<string, boolean>>({}); const [error, setError] = useState<string | null>(null)
 useEffect(() => { if (!id || !user?.id) return; Promise.all([scenarioService.loadScenario(id), scenarioService.listScenarios(user.id)]).then(([loaded, listed]) => { if (!loaded) throw new Error('Scenario not found.'); setLeft(loaded); setItems(listed.filter(item => item.id !== id && !item.is_archived)) }).catch(reason => setError(reason instanceof Error ? reason.message : 'Could not load scenarios.')) }, [id, user?.id])
 useEffect(() => { setRight(null); setResults({}); setFailed({}) }, [id])
 useEffect(() => { if (!left || !right) return; let cancelled = false; Promise.all([fetchScenarioGraph(left.id, { userId: user?.id }), fetchScenarioGraph(right.id, { userId: user?.id })]).then(([a, b]) => { if (!cancelled) { setResults({ [left.id]: resultFromRead(a), [right.id]: resultFromRead(b) }); setFailed({ [left.id]: a.status !== 'graph', [right.id]: b.status !== 'graph' }) } }).catch(() => { if (!cancelled) setFailed({ [left.id]: true, [right.id]: true }) }); return () => { cancelled = true } }, [left, right, user?.id])
 const comparison = useMemo(() => left && right ? diffGraph(graphOf(left), graphOf(right)) : null, [left, right]); if (error) return <main className="p-8">{error}</main>; if (!left) return <main className="p-8">Loading comparison…</main>
 const changed = comparison ? comparison.nodes.added.concat(comparison.nodes.removed) : []; const counts = comparison ? { options: changed.filter(item => value(item, 'kind') === 'option').length, factors: changed.filter(item => value(item, 'kind') === 'factor').length, links: comparison.edges.added.length + comparison.edges.removed.length + comparison.edges.changed.length } : null
 return <main className="min-h-full bg-canvas p-6 md:p-8"><button type="button" onClick={() => navigate(`/scenario/${left.id}`)}><ArrowLeft className="inline w-4 h-4" /> Back to scenario</button><h1 className={`${typography.h2} text-text-header mt-6`}>Compare scenarios</h1><select aria-label="Scenario to compare" value={right?.id ?? ''} onChange={async event => { if (!event.target.value || event.target.value === left.id) return; setRight(await scenarioService.loadScenario(event.target.value)) }}><option value="">Choose another scenario</option>{items.map(item => <option key={item.id} value={item.id}>{item.title || 'Untitled scenario'}</option>)}</select>{!right ? <p>Choose one of your scenarios to see the comparison.</p> : <><div className="grid gap-4 md:grid-cols-2 mt-6"><Side row={left} result={results[left.id] ?? null} failed={failed[left.id] === true} /><Side row={right} result={results[right.id] ?? null} failed={failed[right.id] === true} /></div>{comparison && <section data-testid="comparison-differences"><h2>Model differences</h2>{counts && <p data-testid="comparison-summary">{counts.options} options, {counts.factors} factors and {counts.links} links differ.</p>}<p>Matched by identity first, then by kind and name; unmatched items are added or removed.</p><DiffGroup label="Model items" diff={comparison.nodes} graph={graphOf(left)} edge={false} /><DiffGroup label="Links" diff={comparison.edges} graph={graphOf(left)} edge /></section>}</>}</main> }
