/**
 * Run-turn coaching PROMOTION — gated OFF by
 * `RUN_TURN_COACHING_PROMOTION_ENABLED` (messageComposition.ts), which
 * Reasoning & Coaching flips only after Runtime's click guard is served
 * (programme-docs #63 5819467504).
 *
 * When on, the first block in producer order that is a `run_analysis`
 * coaching card with a target, a producer-authored label + prompt, a routable
 * (or absent) intent and producer freshness `fresh` becomes a TOP-LEVEL point —
 * by displacing the last non-companion point, never by growing the set — and
 * renders its FACE (title, body, action) rather than a collapsed line. Its
 * action is live only while the run-turn currency rule says the card is about
 * the current run.
 *
 * ⚠ THE PAYLOAD IS THE PRODUCER'S v3 GOLDEN FILE, BYTE-FOR-BYTE: CEE #1855 @
 * 940511d9, `src/orchestrator-v5/coaching/__tests__/fixtures/
 * fragile-link-challenge.payload.json` (sha256 bf517e30…edde71), copied
 * without reformatting. Its own `_provenance` is authoritative: generated by
 * the producer's golden-payload test from staging captures reconstructed off
 * one served turn — not a UI route capture. The `explicit_run` card is the
 * subject; the `auto_first_pass` card is pinned as its sibling.
 *
 * The constant is forced ON here through the functions' own option seam
 * (`composeMessage(…, { promoteRunTurnCoaching })`,
 * `planCoachingLines(…, { promoteRunTurnCoaching })`), wrapped at the module
 * boundary so the REAL `InlineBlocks` mounts the promoted composition. With the
 * seam untouched, the real constant decides — which is the OFF arm.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import { AnalysisStateV1Schema, type AnalysisStateV1 } from '@talchain/schemas/boundary'

import fragileLinkFixture from './fixtures/run-turn-coaching-fragile-link.producer-v3.json'
import { InlineBlocks } from '../InlineBlocks'
import { useCanvasStore } from '../../store'
import { adaptTypedCoachingBlock } from '../../../v5/phase3TypedBlocks'
import { FRESHNESS_NOTICE, RUN_TURN_NOTICE } from '../../../v5/blocks/coachingCurrency'
import {
  MAX_POINTS,
  RUN_TURN_COACHING_PROMOTION_ENABLED,
  assertTotalPartition,
  composeMessage,
  firstPromotableActionIndex,
} from '../messageComposition'
import { planCoachingLines } from '../CoachingLine'
import type { ConversationBlock, V5CoachingBlock, V5ExerciseBlock } from '../types'

// ── The seam: force the constant ON for the real InlineBlocks mount ─────────

const promotion = vi.hoisted(() => ({ forced: undefined as boolean | undefined }))

vi.mock('../messageComposition', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../messageComposition')>()
  return {
    ...actual,
    composeMessage: (
      blocks: Parameters<typeof actual.composeMessage>[0],
      headline?: Parameters<typeof actual.composeMessage>[1],
      options?: Parameters<typeof actual.composeMessage>[2],
    ) =>
      actual.composeMessage(
        blocks,
        headline,
        promotion.forced === undefined ? options : { promoteRunTurnCoaching: promotion.forced, ...options },
      ),
  }
})

vi.mock('../CoachingLine', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../CoachingLine')>()
  return {
    ...actual,
    planCoachingLines: (
      blocks: Parameters<typeof actual.planCoachingLines>[0],
      options?: Parameters<typeof actual.planCoachingLines>[1],
    ) =>
      actual.planCoachingLines(
        blocks,
        promotion.forced === undefined ? options : { promoteRunTurnCoaching: promotion.forced, ...options },
      ),
  }
})

/** Deterministic compact-lines presentation (default ON in production). */
vi.mock('../../../flags', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../../../flags')>()
  return { ...actual, isCompactCoachingLinesEnabled: () => true }
})

// ── The producer payload ─────────────────────────────────────────────────────

const RAW_FRAGILE = fragileLinkFixture.explicit_run.blocks[0] as Record<string, unknown>
const RAW_AUTO_FIRST_PASS = fragileLinkFixture.auto_first_pass.blocks[0] as Record<string, unknown>
const FRAGILE_ID = '23150107-6583-5c5a-92d4-548775ea50da'
const RUN_HASH = '2cac03f2a47449be'
const RUN_COMPUTED_AT = '2026-09-24T16:47:26.848Z'
const LATER_RUN_AT = '2026-09-24T17:02:11.004Z'

function adaptFragile(overrides: Record<string, unknown> = {}): V5CoachingBlock {
  const adapted = adaptTypedCoachingBlock({ ...RAW_FRAGILE, ...overrides })
  expect(adapted, 'the producer payload must adapt through the real adapter').not.toBeNull()
  return adapted as V5CoachingBlock
}

/** Ordinary (non-run) coaching cards, distinct titles so none share a line. */
function coaching(n: number): V5CoachingBlock {
  return {
    type: 'v5_coaching',
    block_id: `co_${n}`,
    title: `Coaching card ${n}`,
    body: `Coaching body ${n}`,
    coaching_kind: 'assumption_check',
    source: 'decision_review',
    source_handler: 'decision_review_enricher',
    target_refs: [],
    priority_rank: n,
    freshness: 'fresh',
  }
}

/** The lens companion — a `v5_exercise` (phase3Pacing.isLensCompanionBlock). */
function companion(): V5ExerciseBlock {
  return {
    type: 'v5_exercise',
    block_id: 'ex_companion',
    exercise_kind: 'pre_mortem',
    failure_scenario: 'Imagine it is a year from now and this failed.',
    target_refs: [],
    freshness: 'fresh',
  }
}

/** The run turn: three ordinary cards first, the fragile-link card in overflow. */
function runTurn(fragile: V5CoachingBlock = adaptFragile()): ConversationBlock[] {
  return [coaching(1), coaching(2), coaching(3), fragile]
}

const indices = (entries: ReadonlyArray<{ index: number }>) => entries.map((e) => e.index)

// ── Store: the run-turn currency inputs ──────────────────────────────────────

function verdict(computedAt: string): AnalysisStateV1 {
  return AnalysisStateV1Schema.parse({
    run_state: { kind: 'complete_current', computed_at: computedAt },
    readiness: { status: 'ready', blockers: [] },
    leader_claim: { permitted: true },
    robustness: {},
    usable_for_prose: true,
    usable_for_chips: true,
    usable_for_followup: true,
    requires_rerun: false,
    blocked_unusable: false,
    contradictions: [],
  })
}

function installRun(computedAt: string): void {
  useCanvasStore.setState({
    analysisFreshness: { freshness: 'fresh', currentGraphHash: RUN_HASH },
    analysisFreshnessDirty: false,
    importPendingServerRegistration: false,
    analysisStateV1: verdict(computedAt),
  })
}

function fragileCard(): HTMLElement | null {
  return document.querySelector(`[data-block-id="${FRAGILE_ID}"]`)
}

function fragilePart(suffix: string): HTMLElement | null {
  const card = fragileCard()
  if (!card) return null
  return card.querySelector(`[data-testid="${card.getAttribute('data-testid')}-${suffix}"]`)
}

beforeEach(() => {
  promotion.forced = undefined
  useCanvasStore.setState({
    analysisFreshness: null,
    analysisFreshnessDirty: false,
    importPendingServerRegistration: false,
    analysisStateV1: null,
    nodes: [],
    edges: [],
  })
})
afterEach(() => {
  promotion.forced = undefined
})

// ── The gate ─────────────────────────────────────────────────────────────────

// ── The v3 producer payload itself ───────────────────────────────────────────

describe('the producer’s v3 fragile-link payload', () => {
  function withoutKeys(obj: Record<string, unknown>, keys: readonly string[]): Record<string, unknown> {
    const copy = { ...obj }
    for (const k of keys) delete copy[k]
    return copy
  }

  it('explicit_run carries the v3 framing: an assumption check, not a bias signal', () => {
    expect(fragileLinkFixture.contract_version).toBe('run-turn-coaching/v1')
    const card = adaptFragile()
    expect(card.block_id).toBe(FRAGILE_ID)
    expect(card.coaching_kind).toBe('assumption_check')
    expect(card.title).toBe('Pressure-test a sensitive link')
    expect(card.source_handler).toBe('run_analysis')
    expect(card.created_at).toBe(RUN_COMPUTED_AT)
    expect(card.graph_hash_at_generation).toBe(RUN_HASH)
    expect(String(RAW_FRAGILE.signal_id).endsWith(':explicit_run')).toBe(true)
  })

  it('auto_first_pass adapts, is promotable, and differs from explicit_run ONLY in body / signal_id / block_id', () => {
    const auto = adaptTypedCoachingBlock(RAW_AUTO_FIRST_PASS)
    expect(auto, 'the auto_first_pass card must adapt through the real adapter').not.toBeNull()
    expect(firstPromotableActionIndex([coaching(1), auto as V5CoachingBlock])).toBe(1)
    expect(String(RAW_AUTO_FIRST_PASS.signal_id).endsWith(':auto_first_pass')).toBe(true)

    // Raw: exactly those three keys differ, and each really does differ.
    const differing = ['body', 'signal_id', 'block_id'] as const
    expect(withoutKeys(RAW_AUTO_FIRST_PASS, differing)).toEqual(withoutKeys(RAW_FRAGILE, differing))
    for (const key of differing) expect(RAW_AUTO_FIRST_PASS[key]).not.toBe(RAW_FRAGILE[key])

    // Adapted: `signal_id` is not carried, so only body and block_id differ.
    const explicit = adaptFragile() as unknown as Record<string, unknown>
    const adaptedAuto = auto as unknown as Record<string, unknown>
    expect(withoutKeys(adaptedAuto, ['body', 'block_id'])).toEqual(withoutKeys(explicit, ['body', 'block_id']))
    expect(adaptedAuto.body).toBe(RAW_AUTO_FIRST_PASS.body)
    expect(adaptedAuto.block_id).toBe(RAW_AUTO_FIRST_PASS.block_id)
  })
})

describe('the promotion is gated OFF, and OFF is byte-identical to before', () => {
  it('the constant ships false', () => {
    expect(RUN_TURN_COACHING_PROMOTION_ENABLED).toBe(false)
  })

  it('composeMessage: the fragile-link card stays in overflow, exactly as the prefix rule puts it', () => {
    const blocks = runTurn()
    // Precondition: the card IS promotable — so staying demoted proves the gate,
    // not a fixture that never qualified.
    expect(firstPromotableActionIndex(blocks)).toBe(3)
    const composed = composeMessage(blocks)
    expect(indices(composed.pinned)).toEqual([])
    expect(indices(composed.points)).toEqual([0, 1, 2])
    expect(indices(composed.detail)).toEqual([3])
    expect(JSON.stringify(composed)).toBe(
      JSON.stringify(composeMessage(blocks, null, { promoteRunTurnCoaching: false })),
    )
  })

  it('planCoachingLines: every card keeps its line', () => {
    const blocks = runTurn()
    const plan = planCoachingLines(blocks)
    for (const block of blocks) expect(plan.get(block)).toEqual({ disambiguator: null, collapsible: true })
    expect([...plan.entries()]).toEqual([
      ...planCoachingLines(blocks, { promoteRunTurnCoaching: false }).entries(),
    ])
  })

  it('mounted: the card sits behind "Show 1 more" and, revealed, is a collapsed line', () => {
    installRun(RUN_COMPUTED_AT)
    render(<InlineBlocks blocks={runTurn()} turnId="turn_run" patchBlockStates={new Map()} />)
    expect(fragileCard(), 'demoted: not rendered while the disclosure is closed').toBeNull()
    fireEvent.click(screen.getByTestId('block-detail-toggle'))
    expect(fragileCard()).not.toBeNull()
    expect(screen.getByTestId(`coaching-line-${FRAGILE_ID}`)).toBeInTheDocument()
  })
})

// ── Promotion ON ─────────────────────────────────────────────────────────────

describe('promotion ON — the producer’s fragile-link card becomes a top-level, expanded point', () => {
  it('composeMessage: displaces the last point, never grows the set, partition stays total', () => {
    const blocks = runTurn()
    const composed = composeMessage(blocks, null, { promoteRunTurnCoaching: true })
    expect(indices(composed.points)).toEqual([0, 1, 3])
    expect(indices(composed.detail)).toEqual([2])
    expect(composed.points.length).toBeLessThanOrEqual(MAX_POINTS)
    expect(assertTotalPartition(blocks.length, composed)).toBeNull()
  })

  it('composeMessage: displaces AROUND the lens companion, never the companion itself', () => {
    // [co1, co2, co3, co4, companion, fragile]: the companion reservation takes
    // slot 3 (displacing co3); the promotion then displaces co2, the last
    // non-companion point.
    const blocks: ConversationBlock[] = [
      coaching(1), coaching(2), coaching(3), coaching(4), companion(), adaptFragile(),
    ]
    const composed = composeMessage(blocks, null, { promoteRunTurnCoaching: true })
    expect(indices(composed.points)).toEqual([0, 4, 5])
    expect(indices(composed.detail)).toEqual([1, 2, 3])
    expect(assertTotalPartition(blocks.length, composed)).toBeNull()
  })

  it('composeMessage: a card already among the points moves nothing', () => {
    const blocks: ConversationBlock[] = [adaptFragile(), coaching(1), coaching(2), coaching(3)]
    expect(
      JSON.stringify(composeMessage(blocks, null, { promoteRunTurnCoaching: true })),
    ).toBe(JSON.stringify(composeMessage(blocks, null, { promoteRunTurnCoaching: false })))
  })

  it('planCoachingLines: the promoted card is planned expanded; its neighbours keep their lines', () => {
    const blocks = runTurn()
    const plan = planCoachingLines(blocks, { promoteRunTurnCoaching: true })
    expect(plan.get(blocks[3])?.collapsible).toBe(false)
    for (const i of [0, 1, 2]) expect(plan.get(blocks[i])?.collapsible).toBe(true)
  })

  it('mounted, CURRENT run: top-level, face expanded, action live', () => {
    promotion.forced = true
    installRun(RUN_COMPUTED_AT)
    render(<InlineBlocks blocks={runTurn()} turnId="turn_run" patchBlockStates={new Map()} />)

    // Top level: rendered while the disclosure is still closed.
    const card = fragileCard()
    expect(card, 'the promoted card renders at top level').not.toBeNull()
    expect(screen.getByTestId('block-detail-toggle')).toHaveTextContent('Show 1 more')
    // The displaced card is the one now behind the disclosure.
    expect(document.querySelector('[data-block-id="co_3"]')).toBeNull()

    // Expanded: no line wraps it, and the face carries the producer's own
    // title, body and action — verbatim.
    expect(screen.queryByTestId(`coaching-line-${FRAGILE_ID}`)).toBeNull()
    expect(card?.closest('details')).toBeNull()
    expect(fragilePart('title')).toHaveTextContent(String(RAW_FRAGILE.title))
    expect(fragilePart('body')).toHaveTextContent(String(RAW_FRAGILE.body))
    const chip = fragilePart('action') as HTMLButtonElement
    expect(chip.tagName).toBe('BUTTON')
    expect(chip).toHaveTextContent(String(RAW_FRAGILE.action_label))
    expect(chip.disabled).toBe(false)
    expect(fragilePart('freshness')).toBeNull()

    // Its neighbours are still lines.
    expect(screen.getByTestId('coaching-line-co_1')).toBeInTheDocument()
    expect(screen.getByTestId('coaching-line-co_2')).toBeInTheDocument()
  })

  it('mounted, HISTORICAL (same model, a later run completed): still top-level and expanded, the earlier-run notice speaks, the action is inert', () => {
    promotion.forced = true
    installRun(LATER_RUN_AT)
    render(<InlineBlocks blocks={runTurn()} turnId="turn_run" patchBlockStates={new Map()} />)

    expect(fragileCard()).not.toBeNull()
    expect(screen.queryByTestId(`coaching-line-${FRAGILE_ID}`)).toBeNull()
    expect(fragilePart('freshness')?.textContent).toBe(RUN_TURN_NOTICE.earlier_run)
    expect(fragilePart('freshness')?.textContent).not.toBe(FRESHNESS_NOTICE.stale)
    const chip = fragilePart('action') as HTMLButtonElement
    expect(chip.disabled).toBe(true)
    expect(chip.getAttribute('data-inert')).toBe('true')
  })
})

// ── Never promotable ─────────────────────────────────────────────────────────

describe('what can never be promoted', () => {
  it.each<[string, Record<string, unknown>]>([
    ['a target-less card', { target_refs: [] }],
    ['a card whose intent CEE does not route (confirm_factor)', { action_intent: 'confirm_factor' }],
    ['a card with no action_prompt', { action_prompt: undefined }],
    ['a card with a blank action_label', { action_label: '   ' }],
    ['a card the producer stamped stale', { freshness: 'stale' }],
    ['a card from another handler', { source_handler: 'decision_review_enricher' }],
    ['a card with no source_handler', { source_handler: undefined }],
  ])('%s', (_label, overrides) => {
    const blocks = runTurn(adaptFragile(overrides))
    expect(firstPromotableActionIndex(blocks)).toBe(-1)
    // And forcing the promotion on changes nothing for it.
    expect(JSON.stringify(composeMessage(blocks, null, { promoteRunTurnCoaching: true }))).toBe(
      JSON.stringify(composeMessage(blocks, null, { promoteRunTurnCoaching: false })),
    )
    expect(planCoachingLines(blocks, { promoteRunTurnCoaching: true }).get(blocks[3])?.collapsible).toBe(true)
  })

  it('positive control: an intent CEE DOES route keeps the card promotable', () => {
    const blocks = runTurn(adaptFragile({ action_intent: 'challenge_assumption' }))
    expect(firstPromotableActionIndex(blocks)).toBe(3)
  })

  it('only the FIRST promotable card in producer order is chosen', () => {
    const second = adaptFragile({ block_id: 'second-run-card', title: 'A second run card' })
    const blocks: ConversationBlock[] = [coaching(1), coaching(2), coaching(3), adaptFragile(), second]
    expect(firstPromotableActionIndex(blocks)).toBe(3)
    const composed = composeMessage(blocks, null, { promoteRunTurnCoaching: true })
    expect(indices(composed.points)).toEqual([0, 1, 3])
    expect(indices(composed.detail)).toEqual([2, 4])
  })
})
