// src/lib/__tests__/flagEnv.spec.ts
// =============================================================================
// FLAG_ENV must stay EXACTLY in step with src/flags.ts.
// =============================================================================
//
// `flagFactory` used to snapshot `{ ...import.meta.env }`, which Vite could not
// narrow — so it inlined every `VITE_*` the deploy defined, with values, into the
// flags chunk. FLAG_ENV replaces that with one named literal read per declared
// flag, GENERATED by scripts/generate-flag-env.mjs.
//
// THE FAILURE MODE THIS FILE EXISTS FOR (CLAUDE.md trap 12 — the hand-maintained
// mirror): if a flag is added to `src/flags.ts` and FLAG_ENV is not regenerated,
// that flag's env lookup returns `undefined` and `makeFlag` silently falls through
// to `defaultValue`. A SILENT FLAG FLIP, green everywhere, invisible in review.
// These assertions are DERIVED from src/flags.ts via the same AST walker
// `pnpm flags:check` uses, so they cannot themselves go stale.
// =============================================================================

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { deriveDeclaredFlags } from '../../../tools/ci-guards/flag-deployment-drift.mjs'
import { deriveKeys, renderModule, deriveNetlifyFeatureKeys } from '../../../scripts/generate-flag-env.mjs'
import { FLAG_ENV } from '../flagEnv'

const ROOT = process.cwd()
const flagsSource = readFileSync(path.join(ROOT, 'src/flags.ts'), 'utf8')
const netlifySource = readFileSync(path.join(ROOT, 'netlify.toml'), 'utf8')
const committed = readFileSync(path.join(ROOT, 'src/lib/flagEnv.ts'), 'utf8')

describe('FLAG_ENV covers every declared flag — no silent flag flips', () => {
  const { flags } = deriveDeclaredFlags(flagsSource, 'src/flags.ts')

  it('derives a non-empty declared set (floor — guards a collapsed walker)', () => {
    expect(flags.length).toBeGreaterThanOrEqual(50)
  })

  it('every envKey declared in src/flags.ts is a key of FLAG_ENV', () => {
    const missing = flags.map((f) => f.envKey).filter((k) => !(k in FLAG_ENV))
    // Named, not just counted: a failure must say WHICH flag would silently flip.
    expect(missing).toEqual([])
  })

  it('every VITE_FEATURE_*/VITE_ENABLE_* declared in netlify.toml is a key of FLAG_ENV', () => {
    // exportBundle's debug snapshot enumerates FLAG_ENV; anything declared in
    // netlify.toml must stay reachable there.
    const missing = deriveNetlifyFeatureKeys(netlifySource).filter((k: string) => !(k in FLAG_ENV))
    expect(missing).toEqual([])
  })
})

describe('FLAG_ENV contains ONLY flag keys and Vite build metadata', () => {
  const { builtins, vite } = deriveKeys({ flagsSource, netlifySource })
  const permitted = new Set([...builtins, ...vite])

  it('has no key beyond the derived flag + built-in set', () => {
    expect(Object.keys(FLAG_ENV).filter((k) => !permitted.has(k))).toEqual([])
  })

  it('carries NO credential-shaped variable — the bearer above all', () => {
    // This object is inlined verbatim into the flags chunk, so anything in it is
    // published to every visitor. The original spread put the bearer here.
    expect('VITE_PLOT_BEARER' in FLAG_ENV).toBe(false)
    for (const k of Object.keys(FLAG_ENV)) {
      expect(k, `${k} looks credential-shaped and must not be in the flags chunk`).not.toMatch(
        /BEARER|SECRET|TOKEN|PASSWORD|PRIVATE|_SALT$|ACCESS_CODES/,
      )
    }
  })

  it('keeps BASE_URL FIRST — pnpm flags:check anchors on it', () => {
    // tools/ci-guards/flag-deployment-drift.mjs :: extractDeployedEnv finds the
    // deployed env object by matching `BASE_URL:` and walking BACK to the opening
    // brace, aborting on an intervening `}` or `;`. If BASE_URL stops being the
    // first property, that walk can fail and flags:check goes UNVERIFIED.
    expect(Object.keys(FLAG_ENV)[0]).toBe('BASE_URL')
  })

  it('carries the Vite built-ins flagFactory.spec.ts relies on (e.g. MODE)', () => {
    expect('MODE' in FLAG_ENV).toBe(true)
  })
})

describe('the committed file is not STALE', () => {
  it('matches exactly what the generator would emit today', () => {
    // The `--check` mode of scripts/generate-flag-env.mjs, as a unit test so it
    // runs in the normal suite rather than only in CI.
    expect(committed).toBe(renderModule(deriveKeys({ flagsSource, netlifySource })))
  })

  it('is marked auto-generated so nobody hand-edits it', () => {
    expect(committed).toContain('AUTO-GENERATED FILE')
  })
})
