name: UI CI (Build, Tests, E2E, Evidence)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
concurrency:
  group: ui-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Install
        run: npm ci
      - name: Build
        run: npm run -s build
      - name: Unit tests
        run: npm test -- --reporter=dot
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: ui-build-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: |
            dist/**
            coverage/**
          if-no-files-found: warn
  e2e:
    needs: build-and-unit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chromium, firefox, webkit ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Install
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: E2E (${{ matrix.browser }}) with mild retries
        run: npx playwright test --browser=${{ matrix.browser }} --retries=2
      - name: Upload E2E artefacts (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-e2e-${{ github.run_id }}-${{ github.job }}-${{ matrix.browser }}-${{ github.run_attempt }}
          path: |
            playwright-report/**
            test-results/**
          if-no-files-found: warn
  evidence:
    needs: [ build-and-unit, e2e ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Install
        run: npm ci
      - name: Generate UI pack (default p95=130, flags OFF)
        env:
          UI_P95_MS: "130"
          UI_FEATURES_ON: ""
        run: node tools/gen-ui-evidence-pack.mjs
      - name: Compose unified evidence
        run: node tools/gen-unified-evidence.mjs | tee unified.out
      - name: Print acceptance lines
        run: cat unified.out
      - name: Upload evidence artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-evidence-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}
          path: |
            evidence/pack/**
            docs/evidence/unified/**
            unified.out
          if-no-files-found: warn
