name: Open PR (Release Readiness)

on:
  push:
    branches: [ feat/release-readiness ]

permissions:
  contents: read
  pull-requests: write

jobs:
  open:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create or update PR to main
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const title = 'Release Readiness – Finish Line (CI, Perf p95, Compare UX, Share-Cap E2E, Evidence)';
            let body = '';
            try { body = fs.readFileSync('PR_BODY.md', 'utf8'); } catch {}
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = 'feat/release-readiness';
            const base = 'main';
            // Check for existing open PR from head to base
            const { data: prs } = await github.rest.pulls.list({ owner, repo, state: 'open', head: `${owner}:${head}` });
            if (prs && prs.length > 0) {
              const pr = prs[0];
              // Update title/body if needed
              await github.rest.pulls.update({ owner, repo, pull_number: pr.number, title, body });
              core.setOutput('pr_number', pr.number);
              core.notice(`PR already open: #${pr.number}`);
            } else {
              const { data: pr } = await github.rest.pulls.create({ owner, repo, head, base, title, body });
              core.setOutput('pr_number', pr.number);
              core.notice(`PR created: #${pr.number}`);
            }
