name: UI Evidence Self-Test
on:
  workflow_dispatch:
    inputs:
      ui_p95_ms:
        description: Expected UI p95 (ms)
        default: "130"
        required: true
      ui_features_on:
        description: Comma-separated UI features (leave blank for OFF)
        default: ""
        required: false
permissions:
  contents: read
concurrency:
  group: ui-selftest-${{ github.ref }}
  cancel-in-progress: true
jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install
        run: npm ci

      - name: Build (non-fatal)
        run: npm run -s build || true

      - name: Generate UI pack
        env:
          UI_P95_MS: ${{ github.event.inputs.ui_p95_ms }}
          UI_FEATURES_ON: ${{ github.event.inputs.ui_features_on }}
        run: node tools/gen-ui-evidence-pack.mjs

      - name: Compose unified evidence
        run: node tools/gen-unified-evidence.mjs | tee unified.out

      - name: Print acceptance lines
        run: cat unified.out

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-selftest-${{ github.run_id }}-${{ github.job }}
          path: |
            evidence/pack/**
            docs/evidence/unified/**
            unified.out
          if-no-files-found: warn
